(()=>{
  "use strict";
  const $=selector=>document.querySelector(selector),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char])),n=value=>Number(value||0).toLocaleString("ko-KR");
  const service=window.AfterSignalLiveService;
  let current="relayContracts";
  const operationDefs=[
    {id:"story",name:"현장 기록",eyebrow:"MAIN SIGNAL",tone:"cyan",description:"메인 스토리와 전투를 이어갑니다."},
    {id:"signalSweep",name:"신호 소탕전",eyebrow:"DAILY SWEEP",tone:"cyan",description:"매일 구성이 바뀌는 3파동 전투. 하루 첫 완료 시 성장 재화를 받습니다."},
    {id:"tacticalSimulation",name:"전술 시뮬레이션",eyebrow:"WEEKLY SCORE",tone:"blue",description:"매주 바뀌는 전투 변수 속에서 최고 점수에 도전합니다."},
    {id:"threatInterception",name:"위협체 요격",eyebrow:"CERTIFIED BOSS",tone:"red",description:"보스 등급을 직접 인증하면 그 주에는 빠른 전투로 바로 정산합니다."},
    {id:"noSignalZone",name:"무신호 구역",eyebrow:"WEEKLY SECTOR",tone:"violet",description:"매주 바뀌는 탐사 노드를 차례로 돌파합니다."},
    {id:"relayTower",name:"릴레이 타워",eyebrow:"PERMANENT",tone:"amber",description:"초기화 없이 한 층씩 올라가는 영구 도전 전선입니다."}
  ];
  const LABEL={
    reward:{diamonds:"다이아",credits:"크레딧",battleData:"전투 기록",weaponModules:"무기 모듈",enhancementShards:"무기 모듈",skillManual:"스킬 매뉴얼",coreSignal:"코어 신호",weaponBoxes:"장비 상자",commanderXp:"사령관 경험치"},
    enemy:{renewal_scavenger:"휴면 널 스캐빈저",renewal_aerial:"손상 정비 드론",renewal_aerial_guard:"실드 드론",renewal_mite:"신호 압축체",renewal_plate:"과전류 포탑",renewal_signal_warden:"무신호 감시자",renewal_mira_voice_echo:"미라의 목소리를 가진 것"},
    stage:{"P-01":"정비 구역","P-02":"침수 통로","P-04":"격리 구역","P-07":"무신호 감시 구역"},
    modifier:{enemy_hp_20:"적 체력 +20%",enemy_move_15:"적 이동 속도 +15%",projectile_speed_20:"적 탄속 +20%",shielded_composition:"실드 개체 증가",aerial_heavy:"공중 적 위주",ground_heavy:"지상 적 위주",elite_spawn:"정예 적 출현",core_exposure_minus_20:"코어 노출 -20%",enemy_skill_cooldown_minus_15:"적 스킬 대기 -15%",player_ultimate_charge_minus_15:"필살기 충전 -15%",magazine_minus_50:"장탄 -50%",core_damage_plus_70:"코어 피해 +70%",ultimate_disabled:"필살기 봉인",cover_reduction_plus_50:"엄폐 피해 감소 +50%",enemy_projectile_speed_plus_35:"적 탄속 +35%",reload_speed_minus_20:"재장전 속도 -20%",aerial_only:"공중 적만 출현",ultimate_charge_plus_50:"필살기 충전 +50%",incoming_damage_plus_25:"받는 피해 +25%"},
    node:{START:"시작",COMBAT:"전투",ELITE:"정예",SUPPLY:"보급",RECORD:"기록",RISK:"위험",MIDBOSS:"중간보스",FINAL:"최종"},
    tier:{BRONZE:"브론즈",SILVER:"실버",GOLD:"골드",PLATINUM:"플래티넘"}
  };
  const label=(group,key)=>LABEL[group][key]||String(key??"").replace(/^renewal_/,"").replace(/_/g," ");
  // DIAMOND_ECONOMY_V1 (2026-09-26): amounts come from window.AfterSignalDiamondEconomy; grants go through AfterSignalLiveService.
  const gem=()=>window.AfterSignalDiamondEconomy||null,gemNote=reward=>reward?.diamonds?` · 다이아 +${n(reward.diamonds)}`:"";
  const EXTRA_SOURCES={threatInterception:"위협체 요격",relayTower:"릴레이 타워",signalSweep:"신호 소탕전",noSignalZone:"무신호 구역"},LAST_TOAST_KEY="aftersignal:live-last-toast:v1";
  function announceExtraCombatReward(){try{const row=(service.profile?.rewardLedger||[]).at(-1);if(!row||!EXTRA_SOURCES[row.sourceType]||Date.now()-Number(row.timestamp)>60000||localStorage.getItem(LAST_TOAST_KEY)===row.claimId)return;localStorage.setItem(LAST_TOAST_KEY,row.claimId);toast(`${EXTRA_SOURCES[row.sourceType]} 보상 정산${gemNote(row.reward)}`);}catch{}}
  function toast(message,error=false){const node=$("#toast");if(!node)return;node.textContent=message;node.classList.toggle("live-error",error);node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2200);}
  function sync(){window.__AFTERSIGNAL_SHELTER_QA__?.syncFromFoundation?.();service.refresh();renderHome();renderOperations();if($("#extraContentView")?.classList.contains("active"))renderDetail(current);}
  function showView(id){window.__AFTERSIGNAL_SHELTER_QA__?.showView?.(id);if(!window.__AFTERSIGNAL_SHELTER_QA__)document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.id===id));}
  function ensureView(){if($("#extraContentView"))return;const section=document.createElement("section");section.id="extraContentView";section.className="view live-view";section.innerHTML='<header class="live-head"><div><small class="eyebrow" id="liveEyebrow">EXTRA CONTENT</small><h1 id="liveTitle">릴레이 의뢰</h1><p id="liveDescription"></p></div><button class="live-back" type="button">← 작전 허브</button></header><div id="liveBody" class="live-body"></div>';$(".bottom-nav").before(section);section.querySelector(".live-back").onclick=()=>showView("operations");}
  function open(id){current=id;ensureView();showView("extraContentView");renderDetail(id);}
  function state(){return service.refresh().extraContent;}
  function storyLocked(){return Boolean($("#continueStory")?.disabled);}
  function operationStatus(id){const s=state(),limit=service.configs.economy.threatInterception.dailyAttempts;if(id==="signalSweep")return s.signalSweep.completed?"오늘 완료":"오늘 도전 가능";if(id==="tacticalSimulation")return s.tacticalSimulation.bestScore?`주간 최고 ${n(s.tacticalSimulation.bestScore)}점`:"주간 도전";if(id==="threatInterception")return `빠른 전투 ${limit-s.threatInterception.dailyAttemptsUsed}/${limit}`;if(id==="noSignalZone")return `노드 ${s.noSignalZone.clearedNodes.length}/${s.noSignalZone.nodes.length}`;if(id==="relayTower")return `최고 ${s.relayTower.highestClearedFloor}층`;return storyLocked()?"다음 챕터 준비 중":"진행 가능";}
  function renderOperations(){const host=$("#operationGrid");if(!host)return;const locked=storyLocked();host.innerHTML=operationDefs.map(item=>{const isStory=item.id==="story",off=isStory&&locked;return `<button class="operation-card" data-live-operation="${item.id}" data-tone="${item.tone}" data-locked="${off}"><small>${item.eyebrow}</small><em data-state="${isStory?(off?"LOCKED":"AVAILABLE"):item.id.includes("Sweep")?"DAILY":"WEEKLY"}">${esc(operationStatus(item.id))}</em><h2>${item.name}</h2><p>${item.description}</p><span class="op-cta">${off?"준비 중":isStory?"이어서 진행 →":"입장 →"}</span></button>`}).join("");host.querySelectorAll("[data-live-operation]").forEach(button=>button.onclick=()=>button.dataset.liveOperation==="story"?(storyLocked()?toast("다음 챕터를 준비 중입니다. 그동안 다른 작전으로 대원을 성장시킬 수 있습니다."):$("#continueStory")?.click()):open(button.dataset.liveOperation));const panel=$(".operations-panel");if(panel){const count=panel.querySelector(".status-block b"),small=panel.querySelector(".status-block small");if(small)small.textContent="진행 가능한 작전";if(count)count.textContent=`${operationDefs.length-(locked?1:0)} / ${operationDefs.length}`;if(!panel.querySelector(".preparing-list")){const note=document.createElement("div");note.className="preparing-list";note.innerHTML="<b>준비 중인 작전</b><br>솔로 레이드 기록관 · 릴레이 파견 · 위협체 분석 확장 · 협동 작전 · 이벤트";panel.append(note);}}}
  function renderHome(){const home=$(".home-copy");if(!home)return;let summary=$("#liveSummary");if(!summary){summary=document.createElement("div");summary.id="liveSummary";summary.className="live-summary";home.append(summary);}const s=state(),completed=s.relayContracts.missions.filter(row=>row.progress>=row.target).length,limit=service.configs.economy.threatInterception.dailyAttempts;const claimable=s.relayContracts.missions.some(row=>row.progress>=row.target&&!row.claimed);summary.innerHTML=`<button data-live-home="relayContracts" data-ready="${claimable}"><small>DAILY CONTRACT</small><b>릴레이 의뢰</b><span>${claimable?"수령 가능한 보상 있음":`오늘 ${completed}/3 완료`}</span></button><button data-live-home="signalSweep" data-ready="${!s.signalSweep.completed}"><small>SIGNAL SWEEP</small><b>신호 소탕전</b><span>${s.signalSweep.completed?"오늘 완료":"오늘 첫 보상 받기 가능"}</span></button><button data-live-home="threatInterception"><small>QUICK BATTLE</small><b>위협체 요격</b><span>빠른 전투 ${limit-s.threatInterception.dailyAttemptsUsed}/${limit} 남음</span></button>`;summary.querySelectorAll("button").forEach(button=>button.onclick=()=>open(button.dataset.liveHome));}
  const rewardValue=value=>Array.isArray(value)?value.map(n).join("–"):n(value);
  const rewardHtml=reward=>Object.entries(reward||{}).filter(([key,value])=>value&&!["id","minimumScore"].includes(key)).map(([key,value])=>`<span>${esc(label("reward",key))} +${rewardValue(value)}</span>`).join("");
  function setHead(eyebrow,title,description){$("#liveEyebrow").textContent=eyebrow;$("#liveTitle").textContent=title;$("#liveDescription").textContent=description;}
  function renderContracts(){const s=state().relayContracts,complete=s.missions.filter(row=>row.progress>=row.target).length;setHead("DAILY / WEEKLY NATURAL PROGRESS","릴레이 의뢰","일일 5개 중 3개만 완료하면 됩니다. 원하지 않는 2개는 무시할 수 있습니다.");$("#liveBody").innerHTML=`<article class="live-panel"><small>일일 의뢰 · ${s.dailyKey}</small><h2>오늘 ${complete}/3 완료</h2><div class="mission-list">${s.missions.map(row=>`<div class="mission-row"><div><b>${esc(row.label)}</b><progress max="${row.target}" value="${row.progress}"></progress><span>${n(row.progress)} / ${n(row.target)}</span></div><button data-contract="daily:${row.id}" ${row.progress<row.target||row.claimed?"disabled":""}>${row.claimed?"수령 완료":row.progress>=row.target?"보상 수령":"진행 중"}</button></div>`).join("")}</div><div class="live-actions"><button data-milestone="daily:2" ${complete<2?"disabled":""}>2개 완료 보상 · 무기 모듈</button><button data-milestone="daily:3" ${complete<3?"disabled":""}>3개 완료 보상 · 스킬 매뉴얼${gem()?.DAILY_CONTRACTS?.setComplete?` · 다이아 ${n(gem().DAILY_CONTRACTS.setComplete)}`:""}</button></div></article><article class="live-panel"><small>주간 의뢰 · ${s.weeklyKey} 주</small><div class="mission-list">${s.weeklyMissions.map(row=>`<div class="mission-row"><div><b>${esc(row.label)}</b><progress max="${row.target}" value="${row.progress}"></progress><span>${n(row.progress)} / ${n(row.target)}</span></div><button data-contract="weekly:${row.id}" ${row.progress<row.target||row.claimed?"disabled":""}>${row.claimed?"수령 완료":row.progress>=row.target?"보상 수령":"진행 중"}</button></div>`).join("")}</div><div class="live-actions"><button data-milestone="weekly:${s.weeklyMissions.length}">주간 전체 완료 보상</button></div></article>`;$("#liveBody").querySelectorAll("[data-contract]").forEach(button=>button.onclick=()=>act(()=>{const[kind,id]=button.dataset.contract.split(":");return service.claimContract(kind,id);},"의뢰 보상 수령"));$("#liveBody").querySelectorAll("[data-milestone]").forEach(button=>button.onclick=()=>act(()=>{const[kind,count]=button.dataset.milestone.split(":");return service.claimContractMilestone(kind,+count);},"마일스톤 보상 수령"));}
  function renderSweep(){const s=state().signalSweep,c=s.configuration;setHead("DAILY SEEDED PVE","신호 소탕전","3파동 사이에 강화 1개를 선택하고 최종 보상 1개를 고릅니다. 일일 첫 완료만 보상이 지급됩니다.");$("#liveBody").innerHTML=`<article class="live-panel"><div class="status-line"><span class="status-pill">전장 · ${esc(label("stage",c.background))}</span><span class="status-pill">오늘의 적 변수 · ${esc(label("modifier",c.modifier))}</span><span class="status-pill">중간보스 · ${esc(label("enemy",c.midboss))}</span></div><h2>1파동 → 강화 선택 → 2파동 → 강화 선택 → 최종 파동</h2><div class="live-grid">${c.waves.map((wave,index)=>`<div class="live-card"><small>${index+1}파동</small><h2>적 ${wave.length}기</h2><p>${wave.map(id=>esc(label("enemy",id))).join(" · ")}</p></div>`).join("")}</div><small>하루 첫 완료 보상</small><div class="reward-preview">${rewardHtml({...service.configs.economy.signalSweep.dailyBase,diamonds:gem()?.SIGNAL_SWEEP?.dailyFirstClear})}</div><div class="live-actions"><button data-start-sweep>${s.completed?"다시 도전 (오늘 보상 수령 완료)":"출격"}</button></div></article>`;$("[data-start-sweep]").onclick=()=>service.launch("signalSweep");}
  function renderInterception(){const s=state().threatInterception,claims=service.profile?.rewardClaims||{},e=service.configs.economy.threatInterception,tiers=service.configs.threatInterception.tiers,remaining=Math.max(0,e.dailyAttempts-s.dailyAttemptsUsed);setHead("WEEKLY CERTIFICATION / DAILY QUICK","위협체 요격","등급별 보스를 한 번 직접 격파해 인증하면, 그 주에는 전투 없이 바로 정산하는 빠른 전투를 하루 3회까지 쓸 수 있습니다.");$("#liveBody").innerHTML=`<article class="live-panel"><div class="status-line"><span class="status-pill">${esc(String(s.weeklyKey).replace(/^(\d{4})-W(\d+)$/,"$1년 $2주차"))}</span><span class="status-pill">오늘 빠른 전투 ${remaining}/${e.dailyAttempts}</span><span class="status-pill">최고 인증 ${s.bestTier?s.bestTier+" 등급":"없음"}</span></div><div class="live-grid">${tiers.map(tier=>`<article class="live-card"><small>${tier.id} 등급 · ${esc(label("enemy",tier.bossId))}</small><h2>${s.certification[tier.id]?"인증 완료":"미인증"}</h2><div class="reward-preview">${rewardHtml({...e.tiers[tier.id],diamonds:gem()?.INTERCEPTION?.perClear})}${gem()?.INTERCEPTION?.tierFirstClear&&!claims[`diamond:interceptionTier:${tier.id}`]?`<span>첫 격파 다이아 +${n(gem().INTERCEPTION.tierFirstClear)}</span>`:""}</div><div class="live-actions"><button data-interception="${tier.id}">전투 시작</button><button data-quick="${tier.id}:1" ${s.certification[tier.id]&&remaining>=1?"":"disabled"}>빠른 ×1</button><button data-quick="${tier.id}:3" ${s.certification[tier.id]&&remaining>=3?"":"disabled"}>빠른 ×3</button></div></article>`).join("")}</div></article>`;$("#liveBody").querySelectorAll("[data-interception]").forEach(button=>button.onclick=()=>service.launch("interception",{tier:button.dataset.interception}));$("#liveBody").querySelectorAll("[data-quick]").forEach(button=>button.onclick=()=>act(()=>{const[tier,count]=button.dataset.quick.split(":");return service.quickBattle(tier,+count);},"빠른 전투 정산"));}
  function renderSupply(){const status=service.relaySupplyStatus(),hours=Math.floor(status.hours),minutes=Math.floor((status.hours-hours)*60);setHead("OFFLINE ACCUMULATION · 12H CAP","릴레이 보급소","마지막 수령 시각부터 골드 크레딧과 전투 기록만 누적합니다. 희귀 재화는 생성하지 않습니다.");$("#liveBody").innerHTML=`<article class="live-panel"><small>누적 ${hours}시간 ${minutes}분 / 최대 12시간</small><h2>G ${n(status.credits)} · 전투 기록 ${n(status.battleData)}</h2><progress max="12" value="${status.hours}"></progress><div class="reward-preview"><span>시간당 크레딧 300</span><span>시간당 전투 기록 120</span><span>희귀 재화는 누적되지 않음</span></div><div class="live-actions"><button data-claim-supply ${!status.credits&&!status.battleData?"disabled":""}>원클릭 수령</button></div>${status.rollback?'<p class="live-error">시계 역행이 감지되어 누적을 정지했습니다.</p>':""}</article>`;$("[data-claim-supply]")?.addEventListener("click",()=>act(()=>service.claimRelaySupply(),"릴레이 보급 수령"));}
  function renderTower(){const s=state().relayTower,floors=service.configs.relayTower.initialFloors;setHead("PERMANENT FIRST CLEAR","릴레이 타워","리셋 없는 영구 성장 전선입니다. 완료한 층은 보상 없이 재도전할 수 있습니다.");$("#liveBody").innerHTML=`<article class="live-panel"><small>최고 기록 ${s.highestClearedFloor}층 · 다음 도전 ${Math.min(floors,s.highestClearedFloor+1)}층</small><div class="tower-list">${Array.from({length:floors},(_,i)=>i+1).map(floor=>{const cleared=s.clearedFloors.includes(floor),unlocked=floor<=s.highestClearedFloor+1;return`<button class="tower-floor ${cleared?"cleared":""}" data-floor="${floor}" ${unlocked?"":"disabled"}>${floor}층<small>${cleared?"재도전":(floor%5===0?"보스 · 추가 보상":"첫 클리어 보상")+(gem()?.towerFloor?.(floor)?` · 다이아 ${n(gem().towerFloor(floor))}`:"")}</small></button>`}).join("")}</div></article>`;$("#liveBody").querySelectorAll("[data-floor]").forEach(button=>button.onclick=()=>service.launch("tower",{floor:+button.dataset.floor}));}
  function renderZone(){const s=state().noSignalZone;setHead("WEEKLY SEEDED EXPLORATION","무신호 구역","이번 주 탐사 진행이 저장됩니다. 기록·보급 노드는 누르면 바로 처리되고, 전투 노드는 전투로 돌파합니다. 연결된 다음 노드만 열립니다.");$("#liveBody").innerHTML=`<article class="live-panel"><div class="status-line"><span class="status-pill">탐사 진행 ${s.clearedNodes.length}/${s.nodes.length}</span></div><div class="zone-map">${s.nodes.map(node=>{const cleared=s.clearedNodes.includes(node.id),unlocked=node.id==="START"||cleared||s.clearedNodes.some(id=>(s.nodes.find(row=>row.id===id)?.unlocks||[]).includes(node.id));return`<button class="zone-node ${cleared?"cleared":""} ${s.currentNode===node.id?"current":""}" data-node="${node.id}" ${unlocked?"":"disabled"}><small>${node.id}</small><b>${esc(label("node",node.type))}</b></button>`}).join("")}</div></article>`;$("#liveBody").querySelectorAll("[data-node]").forEach(button=>button.onclick=()=>act(()=>service.enterZoneNode(button.dataset.node),"노드 처리"));}
  function renderSimulation(){const s=state().tacticalSimulation,tiers=service.configs.economy.tacticalSimulation.tiers;setHead("WEEKLY MODIFIER SCORE ATTACK","전술 시뮬레이션","연습은 무제한입니다. 이번 주 최고 점수가 도달한 등급의 보상을 등급마다 한 번씩 받습니다.");$("#liveBody").innerHTML=`<article class="live-panel"><div class="status-line"><span class="status-pill">이번 주 변수</span>${s.modifiers.map(mod=>`<span class="status-pill">${esc(label("modifier",mod))}</span>`).join("")}</div><h2>이번 주 최고 점수 ${n(s.bestScore)}</h2><div class="live-grid">${Object.entries(tiers).map(([tier,row])=>`<article class="live-card"><small>${esc(label("tier",tier))} · ${n(row.minimumScore)}점 이상</small><div class="reward-preview">${rewardHtml(row)}</div><button data-sim-claim="${tier}" ${s.bestScore>=row.minimumScore&&!s.claimedRewardTiers.includes(tier)?"":"disabled"}>${s.claimedRewardTiers.includes(tier)?"수령 완료":"보상 수령"}</button></article>`).join("")}</div><div class="live-actions"><button data-start-sim>연습 / 점수 도전</button></div></article>`;$("[data-start-sim]").onclick=()=>service.launch("simulation");$("#liveBody").querySelectorAll("[data-sim-claim]").forEach(button=>button.onclick=()=>act(()=>service.claimSimulationTier(button.dataset.simClaim),"점수 보상 수령"));}
  function renderDetail(id){ensureView();({relayContracts:renderContracts,signalSweep:renderSweep,threatInterception:renderInterception,relaySupply:renderSupply,relayTower:renderTower,noSignalZone:renderZone,tacticalSimulation:renderSimulation}[id]||renderContracts)();}
  function act(fn,success){try{const result=fn();if(result?.kind||result?.battle)return;toast(success+gemNote(result?.reward));sync();}catch(error){toast(String(error.message||error),true);}}
  async function boot(){try{await service.initialize();ensureView();renderHome();renderOperations();announceExtraCombatReward();const shopCopy=$("#shop .section-head p");if(shopCopy)shopCopy.textContent="일반 성장 재고는 일간·주간 주기로 갱신됩니다. 방치 보급은 시설의 릴레이 보급소에서 수령합니다.";addEventListener("aftersignal:live-reward-granted",()=>window.__AFTERSIGNAL_SHELTER_QA__?.syncFromFoundation?.());const requested=new URLSearchParams(location.search).get("content");if(requested)open(requested);window.AfterSignalLiveUI=Object.freeze({version:"1.0.0",open,render:sync});}catch(error){console.error(error);document.body.dataset.afExtraContentError=String(error.message||error);}}
  boot();
})();
