(()=>{
  "use strict";
  const launch=window.__AF_EXTRA_COMBAT_LAUNCH__;
  const labels={projectile_damage_20:"발사체 피해 +20%",core_damage_30:"CORE 피해 +30%",reload_speed_25:"재장전 속도 +25%",magazine_2:"장탄 +2",shield_recovery_20:"보호막 회복 +20%",ultimate_charge_35:"필살기 충전 +35%",critical_rate_10:"치명타율 +10%",incoming_damage_minus_15:"받는 피해 -15%",impact_stagger_15:"충격 경직 +15%",heavy_multiplier_15:"중량탄 배율 +15%"};
  const recorded={coreHit:0,critical:0,ultimate:0,reload:0,cover:0};
  const ensureUpgrade=()=>{let node=document.getElementById("extraUpgrade");if(node)return node;node=document.createElement("section");node.id="extraUpgrade";node.className="extra-choice";node.innerHTML='<article><small>RELAY ADAPTATION</small><h2>다음 파동 강화 선택</h2><div data-choices></div></article>';document.querySelector(".viewport")?.append(node);return node;};
  function applyUpgrade(id){const runner=window.__AF_COMMON_COMBAT_RUNNER__;if(!runner)return;runner.extraModifiers=runner.extraModifiers||{};runner.extraModifiers[id]=true;if(id==="magazine_2")for(const player of runner.players.filter(Boolean)){player.magazineSize+=2;player.ammo+=2;}if(id==="shield_recovery_20")for(const player of runner.players.filter(Boolean))player.member.shield=Math.min(player.member.maxShield,player.member.shield+20);if(id==="ultimate_charge_35")for(const player of runner.players.filter(Boolean))player.member.ultimateGauge=Math.min(100,player.member.ultimateGauge+35);if(id==="reload_speed_25")for(const player of runner.players.filter(Boolean))player.reloadClock*=.75;if(id==="incoming_damage_minus_15")runner.session.battleSpec.rules.extraIncomingMultiplier=.85;const profile=AfterSignalLiveRewardService.load();profile.extraContent.signalSweep.chosenUpgrades.push(id);AfterSignalLiveRewardService.save(profile);}
  function chooseForWave(wave){const choices=launch?.battle?.upgradeChoices?.[wave-1];if(!choices?.length)return;const runner=window.__AF_COMMON_COMBAT_RUNNER__;if(!runner)return;runner.running=false;const node=ensureUpgrade(),host=node.querySelector("[data-choices]");host.innerHTML=choices.map(id=>`<button data-upgrade="${id}"><b>${labels[id]||id}</b><span>현재 작전에 즉시 적용</span></button>`).join("");node.classList.add("show");host.querySelectorAll("button").forEach(button=>button.onclick=()=>{applyUpgrade(button.dataset.upgrade);node.classList.remove("show");runner.running=true;});}
  addEventListener("aftersignal:objective-progress",event=>{if(event.detail?.stageId!=="P-99"||launch?.kind!=="signalSweep")return;chooseForWave(event.detail.progress);});
  addEventListener("aftersignal:enemy-damaged",event=>{if(event.detail?.stageId!=="P-99")return;if(event.detail.kind==="CORE")recorded.coreHit++;if(event.detail.kind==="CRITICAL")recorded.critical++;});
  addEventListener("aftersignal:ultimate",event=>{if(event.detail?.stageId==="P-99")recorded.ultimate++;});
  async function recordMetrics(){await AfterSignalLiveService.initialize();if(recorded.coreHit)AfterSignalLiveService.recordEvent("coreHit",recorded.coreHit);if(recorded.critical)AfterSignalLiveService.recordEvent("critical",recorded.critical);if(recorded.ultimate)AfterSignalLiveService.recordEvent("ultimate",recorded.ultimate);}
  function rewardChoice(result){const overlay=document.getElementById("extraReward"),host=overlay.querySelector("[data-reward-choices]"),labels={battle_data:"전투 기록 집중",modules:"무기 모듈 확보",hybrid:"크레딧 + 매뉴얼"};host.innerHTML=result.choices.map(id=>`<button data-reward="${id}"><b>${labels[id]||id}</b><span>일일 첫 완료 보상</span></button>`).join("");overlay.classList.add("show");host.querySelectorAll("button").forEach(button=>button.onclick=()=>{AfterSignalLiveService.claimSweepReward(button.dataset.reward);returnToShelter();});}
  function returnToShelter(){window.__AF_COMMON_COMBAT_RUNNER__?.dispose?.("extra-content-exit");localStorage.removeItem("aftersignal:combat:P-99:v1");const shellFrame=window.frameElement?.id==="screen"||window.frameElement?.id==="screen-stage";if(shellFrame)parent.postMessage({type:"aftersignal:navigate",screen:"lobby"},"*");else location.href="lobby.html?view=operations";}
  window.aftersignalCompleteBattle=async()=>{await recordMetrics();const qa=window.__AF_COMMON_COMBAT_QA__||{},result=AfterSignalLiveService.completeCombat({elapsedSeconds:Math.round(((window.__AF_COMMON_COMBAT_RUNNER__?.timeLimitMs||0)-(window.__AF_COMMON_COMBAT_RUNNER__?.timeRemainingMs||0))/1000),damageTaken:qa.eventTrace?.filter?.(entry=>entry.type==="player_damage").length||0});if(result?.requiresRewardChoice)return rewardChoice(result);returnToShelter();};
  window.AfterSignalExtraCombatBridge=Object.freeze({version:"1.0.0",recorded,chooseForWave,returnToShelter});
})();
