(()=>{
  "use strict";
  const PROFILE_KEY="aftersignal:v066:profile";
  const LEGACY_KEYS=["aftersignal:v038:profile","aftersignal:v037:profile"];
  const FOUNDATION_KEY="aftersignal:profile:v3";
  const PENDING_REWARD_KEY="aftersignal:pending-reward:v3";
  const SHELTER=window.AfterSignalShelter;
  const PREVIEW_ONLY=new URLSearchParams(location.search).get("preview")==="1";
  const HOUR=3600000;
  const $=id=>document.getElementById(id);
  const clone=value=>JSON.parse(JSON.stringify(value));
  const n=value=>Number(value||0).toLocaleString("ko-KR");
  const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const now=()=>Date.now();
  const LABELS=SHELTER.labels||{};
  const RESOURCE_META=[["diamonds","다이아","다이아"],["credits","크레딧","G"],["battleData","전투 기록","기록"],["enhancementShards","무기 모듈","모듈"],["skillManual","스킬 매뉴얼","매뉴얼"],["coreSignal","코어 신호","코어"]];
  const RESOURCE_LABEL=Object.fromEntries(RESOURCE_META.map(([key,label])=>[key,label]));
  const SKILL_SLOT={passive:"패시브",skill1:"스킬 1",skill2:"스킬 2",ultimate:"필살기"};
  const SHOP_CATEGORY={CHARACTER:"대원 성장",EQUIPMENT:"장비 강화",SKILL:"스킬 강화"};
  const NAV_ICONS={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/><path d="M10 20v-5h4v5"/></svg>',facility:'<svg viewBox="0 0 24 24"><path d="M12 3 19.5 7.5v9L12 21l-7.5-4.5v-9Z"/><circle cx="12" cy="12" r="3"/></svg>',operations:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="7.5"/><path d="M12 2.5v5M12 16.5v5M2.5 12h5M16.5 12h5"/><circle cx="12" cy="12" r="1.2"/></svg>',shop:'<svg viewBox="0 0 24 24"><path d="M4.5 8h15l-1.3 12h-12.4Z"/><path d="M8.5 8V6.5a3.5 3.5 0 0 1 7 0V8"/></svg>',roster:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8.5" r="3.2"/><path d="M3 20c.6-3.6 3-5.6 6-5.6s5.4 2 6 5.6"/><circle cx="17" cy="9.5" r="2.4"/><path d="M16.2 14.6c2.5.2 4.2 2 4.8 5"/></svg>'};
  const have=key=>Number(profile.resources[key]||0);
  const shortKeys=cost=>Object.entries(cost).filter(([key,value])=>value&&have(key)<value).map(([key])=>key);
  const costHtml=cost=>Object.entries(cost).filter(([,value])=>value).map(([key,value])=>{const short=have(key)<value;return `<span class="${short?"short":""}">${RESOURCE_LABEL[key]||key} ${n(value)}${short?` <small>(보유 ${n(have(key))})</small>`:""}</span>`}).join(" · ");
  const slotName=id=>SHELTER.equipmentSlots.find(slot=>slot.id===id)?.name||id;
  const codeLabel=code=>(LABELS.codes||{})[code]||code;
  let profile;
  let selectedCharacterId="mira";
  let selectedEquipmentId=null;
  let toastTimer=null;
  let idleTicker=null;

  const STORY_ROUTE_REGISTRY={
    "P-05":{label:"P-05 · 끝나지 않은 신호",description:"기억 파편의 발신원을 추적합니다.",screen:"prologueContinue",standalone:"../../scenario/P05/V0.37/AFTERSIGNAL_PROLOGUE_CONTINUE_V0_37_STANDALONE.html",released:true},
    "P-09":{label:"P-09 · 현장 접촉 완료",description:"세라 플린트의 좌석 없는 동행과 현장 접촉 기록이 보존되었습니다.",released:true},
    "P-14":{label:"CHAPTER 01 · 루멘의 잔향",description:"프롤로그를 완료했습니다. 다음 챕터에서는 관측권 아르카디아 스파이어에서 연합 분대와 관리국 판관 오린 베일을 만납니다. 챕터가 열리기 전까지 작전 허브의 반복 작전으로 대원을 성장시킬 수 있습니다.",released:false}
  };

  function characterSeed(id){
    const spec=SHELTER.characters[id];
    return {id,characterId:spec.characterId,name:spec.name,level:1,xp:0,role:spec.typeKo,formation:spec.formation,faction:spec.faction,type:spec.type,weaponId:spec.weapon.id,skills:{passive:1,skill1:1,skill2:1,ultimate:1},equipment:{FRAME_MODULE:null,SIGNAL_MODULE:null,TACTICAL_MODULE:null,PROTECTION_MODULE:null},unlocked:id==="mira"};
  }
  function equipmentSeed(){
    return [
      {instanceId:"EQI-RU-S-01-A",templateId:"EQ-RU-S-01",enhanceLevel:0,moduleSlot:"SIGNAL_MODULE",equippedBy:"mira"},
      {instanceId:"EQI-SC-S-01-A",templateId:"EQ-SC-S-01",enhanceLevel:0,moduleSlot:"SIGNAL_MODULE",equippedBy:"haneul"},
      {instanceId:"EQI-SC-C-01-A",templateId:"EQ-SC-C-01",enhanceLevel:0,moduleSlot:"TACTICAL_MODULE",equippedBy:"sera"},
      {instanceId:"EQI-RU-C-01-A",templateId:"EQ-RU-C-01",enhanceLevel:0,moduleSlot:"TACTICAL_MODULE",equippedBy:null}
    ];
  }
  function defaults(seed=false){
    const seedTime=new Date(now()-(seed?7.5:0)*HOUR).toISOString();
    const characters={mira:characterSeed("mira"),haneul:characterSeed("haneul"),sera:characterSeed("sera"),astra:characterSeed("astra"),tessa:characterSeed("tessa"),naru:characterSeed("naru"),karin:characterSeed("karin"),serin:characterSeed("serin"),luna:characterSeed("luna"),arin:characterSeed("arin"),jaein:characterSeed("jaein"),roa:characterSeed("roa"),noella:characterSeed("noella"),ria:characterSeed("ria"),bomin:characterSeed("bomin"),yunseo:characterSeed("yunseo"),orin:characterSeed("orin"),yura:characterSeed("yura"),narae:characterSeed("narae"),yeonhwa:characterSeed("yeonhwa"),moa:characterSeed("moa"),somi:characterSeed("somi"),bella:characterSeed("bella"),dana:characterSeed("dana"),mei:characterSeed("mei"),yujin:characterSeed("yujin"),iona:characterSeed("iona"),harin:characterSeed("harin"),yumi:characterSeed("yumi"),lumi:characterSeed("lumi"),dabin:characterSeed("dabin"),sion:characterSeed("sion"),liora:characterSeed("liora"),seorin:characterSeed("seorin"),eve:characterSeed("eve"),chaerin:characterSeed("chaerin"),soha:characterSeed("soha"),yuria:characterSeed("yuria"),haejin:characterSeed("haejin"),sea:characterSeed("sea")};
    if(seed)Object.values(characters).forEach(item=>item.unlocked=true);
    if(seed){characters.mira.equipment.SIGNAL_MODULE="EQI-RU-S-01-A";characters.haneul.equipment.SIGNAL_MODULE="EQI-SC-S-01-A";characters.sera.equipment.TACTICAL_MODULE="EQI-SC-C-01-A"}
    return {
      profileVersion:"0.66-mvp",version:"0.66",
      commander:{name:localStorage.getItem("aftersignal:commander-name:v3")||"사령관",level:seed?41:1,xp:0},
      resources:{diamonds:0,credits:seed?24800:0,battleData:seed?12400:0,coreSignal:seed?8:0,enhancementShards:seed?48:0,skillManual:seed?24:0,factionCores:{},typeSeals:{}},
      characters,equipmentInventory:seed?equipmentSeed():[],inventory:{equipmentBoxes:0,weaponBoxes:0},
      unlockedCharacterIds:seed?["mira","haneul","sera","astra","tessa","naru","karin","serin","luna","arin","jaein","roa","noella","ria","bomin","yunseo","orin","yura","yeonhwa","narae","moa","yumi","sion","haejin","eve","sea","seorin","lumi","iona","somi","mei","yuria","soha","liora","bella","dana","chaerin","yujin","harin","dabin"]:["mira"],
      stageClears:{},clears:{},claimed:{},rewardClaims:{},
      shop:{dailyKey:null,weeklyKey:null,dailyBuys:{},weeklyBuys:{}},
      idleRelay:{resourceId:"RELAY_SUPPLY",pendingSupply:0,relaySupply:seed?2100:0,lastAccrualAt:seedTime,activeHourlyRate:120,highestChapterBossCleared:0,clockRollbackDetected:false,quickSupply:{dailyKey:null,used:0}},
      idleShop:{dailyKey:null,weeklyKey:null,dailyBuys:{},weeklyBuys:{}},
      progress:{currentPrologueStage:seed?"P-14":"P-01",prologueComplete:seed,relayBaseUnlocked:seed,temporaryBaseUnlocked:seed}
    };
  }
  function readJson(key){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
  function mergeCharacter(base,source){return {...base,...(source||{}),skills:{...base.skills,...(source?.skills||{})},equipment:{...base.equipment,...(source?.equipment||{})}}}
  function mergeProfile(source,seed=false){
    const d=defaults(seed),p=source||{};
    const merged={...d,...p,profileVersion:"0.66-mvp",version:"0.66",commander:{...d.commander,...(p.commander||{})},resources:{...d.resources,...(p.resources||{}),enhancementShards:Number(p.resources?.enhancementShards??p.resources?.weaponModules??d.resources.enhancementShards),skillManual:Number(p.resources?.skillManual??d.resources.skillManual),diamonds:Math.max(0,Math.floor(Number(p.resources?.diamonds)||0))},characters:{},inventory:{...d.inventory,...(p.inventory||{})},progress:{...d.progress,...(p.progress||{})},shop:{...d.shop,...(p.shop||{}),dailyBuys:{...(p.shop?.dailyBuys||p.shopBuys||{})},weeklyBuys:{...(p.shop?.weeklyBuys||{})}},idleRelay:{...d.idleRelay,...(p.idleRelay||{})},idleShop:{...d.idleShop,...(p.idleShop||{}),dailyBuys:{...(p.idleShop?.dailyBuys||{})},weeklyBuys:{...(p.idleShop?.weeklyBuys||{})}},equipmentInventory:Array.isArray(p.equipmentInventory)?p.equipmentInventory:d.equipmentInventory};
    for(const id of Object.keys(SHELTER.characters))merged.characters[id]=mergeCharacter(d.characters[id],p.characters?.[id]);
    const unlocks=new Set(["mira",...(p.unlockedCharacterIds||[]),...Object.keys(p.characters||{}).filter(id=>p.characters[id]?.unlocked)]);
    if(seed)["haneul","sera","astra","tessa","naru","karin","serin","luna","arin","jaein","roa","noella","ria","bomin","yunseo","orin","yura","yeonhwa","narae","moa","yumi","sion","haejin","eve","sea","seorin","lumi","iona","somi","mei","yuria","soha","liora","bella","dana","chaerin","yujin","harin","dabin"].forEach(id=>unlocks.add(id));
    merged.unlockedCharacterIds=[...unlocks].filter(id=>SHELTER.characters[id]);
    for(const id of merged.unlockedCharacterIds)merged.characters[id].unlocked=true;
    return merged;
  }
  function loadProfile(){
    let raw=readJson(PROFILE_KEY);
    if(!raw)for(const key of LEGACY_KEYS){raw=readJson(key);if(raw)break}
    const foundation=readJson(FOUNDATION_KEY);
    if(foundation){
      raw={...(raw||{}),commander:{...(raw?.commander||{}),...(foundation.commander||{})},resources:{...(raw?.resources||{}),...(foundation.resources||{}),enhancementShards:Number(foundation.resources?.weaponModules??foundation.resources?.enhancementShards??raw?.resources?.enhancementShards??0)},characters:{...(raw?.characters||{}),...(foundation.characters||{})},unlockedCharacterIds:foundation.unlockedCharacterIds||raw?.unlockedCharacterIds,equipmentInventory:foundation.equipmentInventory||raw?.equipmentInventory,inventory:{...(raw?.inventory||{}),...(foundation.inventory||{})},progress:{...(raw?.progress||{}),...(foundation.progress||{}),relayBaseUnlocked:Boolean(foundation.progress?.temporaryBaseUnlocked||foundation.progress?.prologueComplete||raw?.progress?.relayBaseUnlocked)}};
    }
    const merged=mergeProfile(raw,!raw&&PREVIEW_ONLY);merged.gacha=recruitBlockOf(foundation); // GACHA_RECRUIT_V1: ownership is read from the shared profile only
    return merged;
  }
  function saveProfile(){
    localStorage.setItem(PROFILE_KEY,JSON.stringify({...profile,gacha:undefined}));
    const foundation=readJson(FOUNDATION_KEY);
    if(foundation){
      const next={...foundation,commander:{...(foundation.commander||{}),...profile.commander},resources:{...(foundation.resources||{}),credits:Number(profile.resources.credits||0),battleData:Number(profile.resources.battleData||0),coreSignal:Number(profile.resources.coreSignal||0),weaponModules:Number(profile.resources.enhancementShards||0),skillManual:Number(profile.resources.skillManual||0),diamonds:Math.max(0,Math.floor(Number(profile.resources.diamonds)||0))},characters:{...(foundation.characters||{}),...profile.characters},unlockedCharacterIds:profile.unlockedCharacterIds,inventory:{...(foundation.inventory||{}),...profile.inventory},equipmentInventory:profile.equipmentInventory};
      delete next.resources.enhancementShards;
      localStorage.setItem(FOUNDATION_KEY,JSON.stringify(next));
    }
  }

  function localDayKey(date=new Date()){return [date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0")].join("-")}
  function localWeekKey(date=new Date()){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return localDayKey(d)}
  function resetStoresIfNeeded(){
    const day=localDayKey(),week=localWeekKey();
    if(profile.shop.dailyKey!==day){profile.shop.dailyKey=day;profile.shop.dailyBuys={}}
    if(profile.shop.weeklyKey!==week){profile.shop.weeklyKey=week;profile.shop.weeklyBuys={}}
    if(profile.idleShop.dailyKey!==day){profile.idleShop.dailyKey=day;profile.idleShop.dailyBuys={}}
    if(profile.idleShop.weeklyKey!==week){profile.idleShop.weeklyKey=week;profile.idleShop.weeklyBuys={}}
  }
  function nextMidnight(){const d=new Date();d.setHours(24,0,0,0);return d.getTime()}
  function formatDuration(ms){const seconds=Math.max(0,Math.floor(ms/1000)),h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return [h,m,s].map(value=>String(value).padStart(2,"0")).join(":")}
  function commanderSupplyBonus(level=profile.commander.level){const policy=SHELTER.idleSupplyPolicy,tiers=Math.max(0,Math.floor((Number(level||1)-1)/policy.commanderTierInterval));return {tiers,rate:tiers*policy.commanderTierBonusRate,multiplier:1+tiers*policy.commanderTierBonusRate,nextLevel:policy.commanderTierFirstLevel+tiers*policy.commanderTierInterval}}
  function baseHourlyRate(level=profile.commander.level){const policy=SHELTER.idleSupplyPolicy,commanderLevel=Math.max(1,Number(level||1)),boss=Math.max(0,Number(profile.idleRelay.highestChapterBossCleared||0),/* CAMPAIGN_CH01_05_V1 */Number(window.AfterSignalCampaign?.chapterBossesCleared?.()||0));return policy.baseHourlyRate+policy.perCommanderLevelHourlyIncrease*(commanderLevel-1)+policy.bossClearHourlyIncrease*Math.min(policy.bossClearCap,boss)}
  function activeHourlyRate(){const base=baseHourlyRate(),bonus=commanderSupplyBonus();return Math.round(base*bonus.multiplier)}
  function accruedAt(time=now()){
    const idle=profile.idleRelay,last=Date.parse(idle.lastAccrualAt||new Date(time).toISOString());
    let elapsed=Math.max(0,time-last);
    if(time<last){elapsed=0;idle.clockRollbackDetected=true}
    const hours=elapsed/HOUR,full=Math.min(hours,24),half=Math.min(Math.max(hours-24,0),24),quarter=Math.min(Math.max(hours-48,0),24),rate=activeHourlyRate();
    return {elapsed,rate,pending:Math.floor(Number(idle.pendingSupply||0)+rate*full+rate*.5*half+rate*.25*quarter),efficiency:hours>=72?0:hours>=48?.25:hours>=24?.5:1};
  }
  function grantResources(grant){for(const [key,value] of Object.entries(grant)){if(key==="equipmentBox")grantEquipmentBox(value);else profile.resources[key]=Number(profile.resources[key]||0)+value}}
  function grantEquipmentBox(count=1){for(let i=0;i<count;i++){const character=SHELTER.characters[selectedCharacterId]||SHELTER.characters.mira,template=Object.values(SHELTER.equipmentCatalog).find(item=>item.faction===character.faction&&item.type===character.type)||Object.values(SHELTER.equipmentCatalog)[0],slot=SHELTER.equipmentSlots[(profile.equipmentInventory.length+i)%SHELTER.equipmentSlots.length].id;profile.equipmentInventory.push({instanceId:`EQI-${template.templateId}-${Date.now()}-${i}`,templateId:template.templateId,enhanceLevel:0,moduleSlot:slot,equippedBy:null})}}

  function toast(text){$("toast").textContent=text;$("toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1900)}
  function navigate(screen,standalone){if(parent!==window)parent.postMessage({type:"aftersignal:navigate",screen},"*");else location.href=standalone}
  function activeStoryRoute(){/* CAMPAIGN_CH01_05_V1: after the prologue the main story continues on the campaign map */const campaign=window.AfterSignalCampaign;if(campaign&&(campaign.prologueDone()||profile.progress.prologueComplete===true)){const next=campaign.frontier(),stage=next?campaign.byId.get(next):null,chapter=stage?campaign.chapters.get(stage.chapter):null,last=campaign.chapters.get(campaign.data.chapters[campaign.data.chapters.length-1].id);return{stageId:next||"CAMPAIGN-COMPLETE",label:stage?`CHAPTER ${String(chapter.no).padStart(2,"0")} · ${stage.code} ${stage.title}`:`CHAPTER ${String(last.no).padStart(2,"0")} 완료`,description:stage?`${chapter.title} — 다음 작전을 이어서 진행합니다.`:`다음 챕터는 준비 중입니다. 작전 지도에서 지난 작전을 다시 볼 수 있습니다.`,screen:"campaign",standalone:"campaign.html",released:true}}let foundation=readJson(FOUNDATION_KEY),pending=readJson(PENDING_REWARD_KEY);const raw=String(pending?.stage||foundation?.progress?.currentPrologueStage||profile.progress.currentPrologueStage||"P-05").toUpperCase(),stage=raw.replace(/^P(\d+)$/,"P-$1"),flow=window.AfterSignalStageFlow?.routeForStage?.(stage),next=flow?window.AfterSignalStageFlow.routeForStage(flow.nextStage):null,legacy=STORY_ROUTE_REGISTRY[stage];return{stageId:stage,label:legacy?.label||stage+" · 다음 기록",description:legacy?.description||"다음 기록을 준비 중입니다.",screen:next?.entry||legacy?.screen||"",standalone:next?.entry?next.entry+".html":legacy?.standalone||"",released:Boolean(next?.entry||legacy?.released)}}
  function unlocked(){const route=window.AfterSignalStageFlow?.routeForStage?.(activeStoryRoute().stageId);return PREVIEW_ONLY||profile.progress.relayBaseUnlocked===true||profile.progress.temporaryBaseUnlocked===true||profile.progress.prologueComplete===true||route?.nextStage==="TEMPORARY-BASE"}
  function showView(id){document.querySelectorAll(".view").forEach(view=>{view.classList.toggle("active",view.id===id);if(view.id===id)view.scrollTop=0});document.querySelectorAll(".nav").forEach(button=>button.classList.toggle("active",button.dataset.nav===id||(id==="detail"&&button.dataset.nav==="roster")));if(id==="shop")renderShop();if(id==="detail")renderDetail()}
  function renderTop(){$("commanderName").textContent=profile.commander.name;$("commanderLevel").textContent=profile.commander.level;$("resources").innerHTML=RESOURCE_META.slice(0,5).map(([key,label,short])=>`<div class="chip" data-resource="${key}" title="${label} ${n(have(key))}"><i></i><small class="full">${label}</small><small class="short">${short}</small>${n(have(key))}</div>`).join("")}
  function renderStoryRoute(){const route=activeStoryRoute(),button=$("continueStory");$("storyStage").textContent=route.label;$("storyStage").nextElementSibling.textContent=route.description;button.disabled=!route.released;button.textContent=route.released?"메인 스토리 계속":"다음 챕터 준비 중";button.dataset.screen=route.screen;button.dataset.standalone=route.standalone;let actions=button.closest(".story-actions");if(!actions){actions=document.createElement("div");actions.className="story-actions";button.before(actions);actions.append(button)}let alt=$("storyAlt");if(!alt){alt=document.createElement("button");alt.id="storyAlt";alt.type="button";alt.className="primary story-alt";alt.textContent="작전 허브로 이동";alt.onclick=()=>showView("operations");actions.append(alt)}alt.hidden=route.released;$("home").dataset.story=route.released?"ready":"pending"}
  function facilityStatus(facility){if(facility.id==="supply")return "최대 12시간 누적 · 수령 가능";if(facility.id==="quarters")return `합류 대원 ${unlockedCharacterIds().length}명`;return facility.statusKo||facility.status}
  function selectFacility(id){const facility=SHELTER.facilities.find(item=>item.id===id)||SHELTER.facilities[0],action={supply:["릴레이 보급 수령",()=>window.AfterSignalLiveUI?.open?.("relaySupply")],workshop:["대원 장비 관리",()=>showView("roster")],quarters:["대원 관리 열기",()=>showView("roster")],command:["작전 허브 열기",()=>showView("operations")]}[facility.id];document.querySelectorAll("[data-facility]").forEach(node=>node.classList.toggle("selected",node.dataset.facility===facility.id));$("facilityName").textContent=facility.name;$("facilityDescription").textContent=facility.description;$("facilityStatus").textContent=facilityStatus(facility);$("facilityStatus").dataset.code=facility.id==="supply"?"12H CAP · READY":facility.status;$("facilityPrimary").textContent=action?action[0]:"준비 중인 시설";$("facilityPrimary").disabled=!action;$("facilityPrimary").onclick=()=>{if(action)action[1]();else toast(facility.name+"은 준비 중인 시설입니다.")};let hint=document.querySelector(".facility-panel .hint");if(!hint){hint=document.createElement("p");hint.className="hint";document.querySelector(".facility-panel").append(hint)}hint.textContent="지도에서 시설을 누르면 상태와 바로가기가 표시됩니다."}
  function renderFacilities(){$("facilityMap").innerHTML=SHELTER.facilities.map(item=>`<button class="facility-node" data-facility="${item.id}" data-accent="${item.accent}" style="--node-x:${item.x};--node-y:${item.y}"><small>${item.eyebrow}</small><b>${esc(item.name)}</b><span>${esc(facilityStatus(item))}</span></button>`).join("");document.querySelectorAll("[data-facility]").forEach(node=>node.onclick=()=>selectFacility(node.dataset.facility));selectFacility("command")}
  function renderOperations(){$("operationGrid").innerHTML=SHELTER.operations.map(item=>`<button class="operation-card" data-operation="${item.id}" data-tone="${item.tone}"><small>${item.eyebrow}</small><em>${item.state}</em><h2>${esc(item.name)}</h2><p>${esc(item.description)}</p></button>`).join("");document.querySelectorAll("[data-operation]").forEach(node=>node.onclick=()=>{const item=SHELTER.operations.find(entry=>entry.id===node.dataset.operation);if(item.id==="story")return $("continueStory").click();toast(item.name+"은 준비 중입니다.")})}

  function stockRemaining(item,store=profile.shop){const buys=item.period==="weekly"?store.weeklyBuys:store.dailyBuys;return Math.max(0,item.stock-Number(buys[item.id]||0))}
  function renderDailyShop(){
    $("dailyResetLabel").textContent="갱신까지 "+formatDuration(nextMidnight()-now());
    $("shopHostLine").textContent=`보유 크레딧 G ${n(profile.resources.credits)} · 일일 재고는 매일 00:00, 주간 재고는 월요일에 갱신됩니다.`;
    $("shopGrid").innerHTML=SHELTER.shopStock.map(item=>{const remain=stockRemaining(item),sold=remain<=0,poor=!sold&&profile.resources.credits<item.price;return `<article class="shop-card ${sold?"sold-out":""} ${poor?"insufficient":""}"><div class="shop-icon">${item.icon}</div><div class="stock-badge">${item.period==="daily"?"일일 재고":"주간 재고"} ${remain}/${item.stock}</div><span class="eyebrow">${SHOP_CATEGORY[item.category]||item.category}</span><h3>${esc(item.name)}</h3><p>${esc(item.desc)}</p><button class="primary" data-buy="${item.id}" ${sold?"disabled":""}>${sold?"품절":poor?`G ${n(item.price)} · 크레딧 부족`:`G ${n(item.price)} 구매`}</button></article>`}).join("");
    document.querySelectorAll("[data-buy]").forEach(button=>button.onclick=()=>buyShop(button.dataset.buy));
  }
  function buyShop(id){const item=SHELTER.shopStock.find(entry=>entry.id===id),remain=stockRemaining(item);if(remain<=0)return toast("현재 재고가 모두 소진되었습니다.");if(profile.resources.credits<item.price)return toast(`크레딧이 부족합니다. (필요 G ${n(item.price)} / 보유 G ${n(profile.resources.credits)})`);profile.resources.credits-=item.price;grantResources(item.grant);const buys=item.period==="weekly"?profile.shop.weeklyBuys:profile.shop.dailyBuys;buys[id]=Number(buys[id]||0)+1;saveProfile();window.AfterSignalLiveService?.recordEvent?.("shopPurchase",1);render();toast(item.name+" 구매 완료")}
  function idleStock(item){const tier=Math.floor(Math.max(activeHourlyRate()-240,0)/80),stock=item.baseStock+(item.period==="weekly"?2*tier:tier),buys=item.period==="weekly"?profile.idleShop.weeklyBuys:profile.idleShop.dailyBuys;return {stock,remain:Math.max(0,stock-Number(buys[item.id]||0))}}
  function renderIdle(){
    const accrued=accruedAt(),hours=accrued.elapsed/HOUR,bonus=commanderSupplyBonus(),nextThreshold=hours<24?24:hours<48?48:72,effLabel=accrued.efficiency===1?"정상 효율 · 100%":accrued.efficiency===.5?"장기 미접속 · 50%":accrued.efficiency===.25?"최종 누적 · 25%":"생산 정지 · 0%";
    $("pendingSupply").textContent=n(accrued.pending);/* LOBBY_IDLE_CLAIM_V1: the home strip mirrors the idle dashboard */if($("homeIdle")){$("homeIdle").dataset.ready=String(accrued.pending>0);$("homeIdlePending").textContent=n(accrued.pending);$("homeIdleInfo").textContent=`시간당 ${n(accrued.rate)} P · 보유 ${n(profile.idleRelay.relaySupply)} P${accrued.efficiency===1?"":accrued.efficiency>0?` · 효율 ${Math.round(accrued.efficiency*100)}%`:" · 생산 정지"}`;$("homeIdleProgress").style.width=`${Math.min(100,hours/72*100)}%`;$("homeIdleClaim").disabled=accrued.pending<=0;$("homeIdleClaim").textContent=accrued.pending>0?"받기":"누적 대기 중";}$("pendingBadge").textContent=accrued.pending?`+${n(accrued.pending)} P`:"";$("relaySupply").textContent=n(profile.idleRelay.relaySupply);$("hourlyRate").textContent=accrued.rate;$("idleEfficiency").textContent=`${effLabel} · 지휘 링크 +${Math.round(bonus.rate*100)}%`;
    $("nextDecay").textContent=hours>=72?"정지":formatDuration((nextThreshold-hours)*HOUR);$("stopAt").textContent=hours>=72?"정지":formatDuration((72-hours)*HOUR);$("idleProgress").style.width=`${Math.min(100,hours/72*100)}%`;$("claimIdle").disabled=accrued.pending<=0;$("claimIdle").textContent=accrued.pending>0?`보급 ${n(accrued.pending)} P 받기`:"누적 대기 중";
    $("idleExchangeGrid").innerHTML=SHELTER.idleExchange.map(item=>{const state=idleStock(item),sold=state.remain<=0;return `<article class="exchange-card ${sold?"sold-out":""}"><div class="shop-icon">${item.icon}</div><span class="eyebrow">${item.period.toUpperCase()} · ${state.remain}/${state.stock}</span><h3>${esc(item.name)}</h3><button class="primary" data-exchange="${item.id}" ${sold?"disabled":""}>${sold?"SOLD OUT":n(item.cost)+" P"}</button></article>`}).join("");document.querySelectorAll("[data-exchange]").forEach(button=>button.onclick=()=>exchangeIdle(button.dataset.exchange));
  }
  function claimIdle(){const accrued=accruedAt();if(accrued.pending<=0)return;profile.idleRelay.relaySupply=Number(profile.idleRelay.relaySupply||0)+accrued.pending;profile.idleRelay.pendingSupply=0;profile.idleRelay.lastAccrualAt=new Date().toISOString();profile.idleRelay.activeHourlyRate=activeHourlyRate();saveProfile();render();toast(`릴레이 보급 ${n(accrued.pending)} P 수령`)}
  function exchangeIdle(id){const item=SHELTER.idleExchange.find(entry=>entry.id===id),state=idleStock(item);if(state.remain<=0)return toast("교환 재고가 소진되었습니다.");if(profile.idleRelay.relaySupply<item.cost)return toast("릴레이 보급 포인트가 부족합니다.");profile.idleRelay.relaySupply-=item.cost;grantResources(item.grant);const buys=item.period==="weekly"?profile.idleShop.weeklyBuys:profile.idleShop.dailyBuys;buys[id]=Number(buys[id]||0)+1;saveProfile();render();toast(item.name+" 교환 완료")}
  function selectShopTab(id){document.querySelectorAll("[data-shop-tab]").forEach(button=>button.classList.toggle("active",button.dataset.shopTab===id));$("dailyShopPane").classList.toggle("active",id==="daily");$("idleShopPane").classList.toggle("active",id==="idle");if(id==="idle")renderIdle();else renderDailyShop()}
  function renderShop(){resetStoresIfNeeded();renderDailyShop();renderIdle()}

  function unlockedCharacterIds(){if(recruitMode())return ownedCrewIds();return profile.unlockedCharacterIds.filter(id=>SHELTER.characters[id]&&profile.characters[id]?.unlocked)}
  function portraitClass(spec){return spec.presentationPolicy==="SEATED_REAR_COMBAT_PREVIEW_ONLY"?"portrait-rear":/\/characters\//.test(spec.portrait)?"portrait-full":""}
  function renderRoster(){const ids=unlockedCharacterIds(),recruit=recruitMode(),cards=ids.map(id=>{const spec=SHELTER.characters[id],character=profile.characters[id];return `<button class="portrait-card" data-character="${id}" data-rarity="${spec.rarity||""}"><span class="rarity">${spec.rarity||""}</span><div class="portrait-frame"><img class="${portraitClass(spec)}" src="${spec.portrait}" alt="${esc(spec.name)} 얼굴 초상화"></div><div class="meta"><small>${esc(spec.factionKo||spec.faction)}</small><b>${esc(spec.name)}</b>${starsHtml(id)}<span>LV.${character.level} · ${spec.typeKo} · ${spec.formation}</span></div></button>`});if(recruit){if(!ids.length)cards.push(`<button type="button" class="portrait-card recruit-empty" data-recruit-open="first"><div class="locked-mark">＋</div><div class="meta"><small>RELAY RECRUIT</small><b>첫 모집</b><span>대원 모집에서 첫 대원을 영입하세요</span></div></button>`);for(const id of recruitPoolIds().filter(id=>!ids.includes(id))){const spec=SHELTER.characters[id];cards.push(`<button type="button" class="portrait-card locked recruit-locked" data-recruit-open="${id}" data-rarity="${spec.rarity||""}" aria-label="${esc(spec.name)} 미보유 · 대원 모집 열기"><span class="rarity">${spec.rarity||""}</span><div class="portrait-frame"><img class="${portraitClass(spec)}" src="${spec.portrait}" alt="" loading="lazy"></div><div class="meta"><small>미보유</small><b>${esc(spec.name)}</b><span>대원 모집으로 합류</span></div></button>`)}}else while(cards.length<5)cards.push(`<article class="portrait-card locked"><div class="locked-mark">＋</div><div class="meta"><small>STORY LOCK</small><b>미합류 대원</b><span>시나리오 합류 후 해금</span></div></article>`);$("rosterGrid").innerHTML=cards.join("");renderRosterTools(recruit,ids.length);document.querySelectorAll("[data-character]").forEach(button=>button.onclick=()=>{selectedCharacterId=button.dataset.character;showView("detail")})}
  function characterCost(target){const band=Math.floor((target-1)/20);return{credits:700+200*target+3000*band+1000*band*(band-1)/2,battleData:300+150*target+1200*band+400*band*(band-1)/2,coreSignal:(target%10===0?2+target/10:0)+(target>=21&&(target-1)%20===0?4+2*band:0)}}
  function skillCost(target){return{credits:900+350*target,skillManual:target}}
  function equipmentCost(target){return[{credits:0,enhancementShards:0},{credits:2000,enhancementShards:5},{credits:4000,enhancementShards:10},{credits:8000,enhancementShards:20},{credits:14000,enhancementShards:35},{credits:22000,enhancementShards:55}][target]||null}
  function equipmentById(id){return profile.equipmentInventory.find(item=>item.instanceId===id)}
  function renderDetail(){
    const spec=SHELTER.characters[selectedCharacterId]||SHELTER.characters.mira,character=profile.characters[selectedCharacterId]||profile.characters.mira;
    $("detailStanding").src=spec.standing;$("detailStanding").alt=spec.name+" 스탠딩 일러스트";$("detailCode").textContent=`${spec.characterId} · ${spec.factionKo}`;$("detailName").textContent=spec.name;$("detailRole").textContent=`${spec.rarity||""} · ${spec.typeKo} · ${spec.formation}`;renderDetailSwitch();renderDetailStars(profile.characters[selectedCharacterId]?selectedCharacterId:"mira");
    $("uniqueWeapon").innerHTML=`<article class="unique-weapon"><div><small>UNIQUE / LV.${character.level}</small><b>${esc(spec.weapon.name)}</b><span>기본 피해 ${spec.weapon.damage} · 장탄 ${spec.weapon.magazine}</span></div><strong>전용 무기</strong></article>`;
    $("equipmentGrid").innerHTML=SHELTER.equipmentSlots.map(slot=>{const instance=equipmentById(character.equipment[slot.id]),template=instance?SHELTER.equipmentCatalog[instance.templateId]:null;return `<button class="module-slot ${instance?"equipped":"empty"}" data-slot="${slot.id}"><small>${slot.name}</small><b>${template?esc(template.name):"장비 없음"}</b><span>${template?`+${instance.enhanceLevel} · ${template.stat}`:slot.hint}</span></button>`}).join("");document.querySelectorAll("[data-slot]").forEach(button=>button.onclick=()=>openEquipmentPicker(button.dataset.slot));
    $("equipmentInventory").innerHTML=`<h3>보유 장비 <small>${profile.equipmentInventory.length}</small></h3><div class="inventory-strip">${profile.equipmentInventory.length?profile.equipmentInventory.map(item=>{const template=SHELTER.equipmentCatalog[item.templateId];return `<button data-inventory="${item.instanceId}"><b>${esc(template?.name||item.templateId)}</b><small>+${item.enhanceLevel} · ${esc(slotName(item.moduleSlot))}${item.equippedBy?" · 장착 중":""}</small></button>`}).join(""):"<p>보유 장비가 없습니다. 상점의 장비 상자에서 획득할 수 있습니다.</p>"}</div>`;document.querySelectorAll("[data-inventory]").forEach(button=>button.onclick=()=>openEquipment(button.dataset.inventory));
    const cost=characterCost(character.level+1),capped=character.level>=profile.commander.level,lacking=shortKeys(cost).length>0;$("levelInfo").innerHTML=`<div class="level-hero"><strong>LV.${character.level}</strong><span>/ 상한 LV.${profile.commander.level}</span><i style="--level:${Math.min(100,character.level/profile.commander.level*100)}%"></i></div><p class="level-note">대원 레벨은 사령관 레벨까지 올릴 수 있습니다. 사령관 레벨은 작전을 완료하면 오릅니다.</p><div class="statline"><span>HP 보정</span><b>+${(Math.max(0,character.level-1)*5.5).toFixed(1)}%</b></div><div class="statline"><span>기본 공격 보정</span><b>+${Math.max(0,(character.level-1)*8)}%</b></div>${starStatline(selectedCharacterId)}${combatStatline(selectedCharacterId,character.level)}<div class="cost">${capped?"사령관 레벨 상한에 도달했습니다.":`다음 레벨 필요 재화 · ${costHtml(cost)}`}</div><button id="levelCharacter" class="primary">${capped?"사령관 레벨 상한":lacking?"재화 부족":`LV.${character.level+1} 레벨업`}</button>`;$("levelCharacter").disabled=capped||lacking;$("levelCharacter").onclick=levelCharacter;
    $("skillRows").innerHTML=Object.entries(spec.skills).map(([id,label])=>{const level=character.skills[id],cost=skillCost(level+1),max=level>=10,lacking=!max&&shortKeys(cost).length>0;return `<article class="skill-row"><i>${label[0]}</i><div><small class="slot">${SKILL_SLOT[id]||id}</small><b>${label[1]} · LV.${level}</b><small>${max?"최대 레벨":costHtml(cost)}</small></div><button class="primary" data-skill="${id}" ${max||lacking?"disabled":""}>${max?"MAX":lacking?"재화 부족":"강화"}</button></article>`}).join("");document.querySelectorAll("[data-skill]").forEach(button=>button.onclick=()=>levelSkill(button.dataset.skill));
  }
  function levelCharacter(){const character=profile.characters[selectedCharacterId],target=character.level+1,cost=characterCost(target);if(target>profile.commander.level)return toast("사령관 레벨이 캐릭터 성장 상한입니다.");for(const key of ["credits","battleData","coreSignal"])if(Number(profile.resources[key]||0)<cost[key])return toast("대원 성장 재화가 부족합니다.");for(const key of ["credits","battleData","coreSignal"])profile.resources[key]-=cost[key];character.level=target;saveProfile();window.AfterSignalLiveService?.recordEvent?.("characterGrowth",1);render();toast(`${character.name} LV.${target} 달성`)}
  function levelSkill(id){const character=profile.characters[selectedCharacterId],target=character.skills[id]+1,cost=skillCost(target);if(target>10)return;if(profile.resources.credits<cost.credits||profile.resources.skillManual<cost.skillManual)return toast("스킬 성장 재화가 부족합니다.");profile.resources.credits-=cost.credits;profile.resources.skillManual-=cost.skillManual;character.skills[id]=target;saveProfile();window.AfterSignalLiveService?.recordEvent?.("characterGrowth",1);render();toast(`스킬 LV.${target} 강화 완료`)}
  function openEquipmentPicker(slotId){const candidates=profile.equipmentInventory.filter(item=>item.moduleSlot===slotId);$("weaponTitle").textContent=SHELTER.equipmentSlots.find(slot=>slot.id===slotId)?.name||"장비 선택";$("modalWeaponInfo").innerHTML=candidates.length?`<div class="equipment-choice">${candidates.map(item=>{const template=SHELTER.equipmentCatalog[item.templateId];return `<button data-equip="${item.instanceId}" data-slot-target="${slotId}"><b>${esc(template?.name||item.templateId)} +${item.enhanceLevel}</b><small>${codeLabel(template?.faction)} / ${codeLabel(template?.type)} · ${template?.stat}</small></button>`}).join("")}</div>`:'<p class="empty-copy">이 슬롯에 장착할 장비가 없습니다.</p>';$("upgradeWeapon").hidden=true;document.querySelectorAll("[data-equip]").forEach(button=>button.onclick=()=>equipItem(button.dataset.equip,button.dataset.slotTarget));$("weaponModal").classList.add("open")}
  function equipItem(instanceId,slotId){const character=profile.characters[selectedCharacterId],previous=equipmentById(character.equipment[slotId]),item=equipmentById(instanceId);if(previous)previous.equippedBy=null;if(item.equippedBy&&profile.characters[item.equippedBy])for(const slot of SHELTER.equipmentSlots)if(profile.characters[item.equippedBy].equipment[slot.id]===item.instanceId)profile.characters[item.equippedBy].equipment[slot.id]=null;item.equippedBy=selectedCharacterId;character.equipment[slotId]=instanceId;saveProfile();closeEquipment();render();toast(`${SHELTER.equipmentCatalog[item.templateId].name} 장착`)}
  function openEquipment(instanceId){const item=equipmentById(instanceId),template=SHELTER.equipmentCatalog[item.templateId],cost=equipmentCost(item.enhanceLevel+1);selectedEquipmentId=instanceId;$("weaponTitle").textContent=template.name;$("modalWeaponInfo").innerHTML=`<div class="statline"><span>진영 / 타입</span><b>${codeLabel(template.faction)} · ${codeLabel(template.type)}</b></div><div class="statline"><span>강화 단계</span><b>+${item.enhanceLevel} / +5</b></div><div class="statline"><span>고정 옵션</span><b>${template.stat}</b></div>${cost?`<div class="cost">강화 필요 재화 · ${costHtml(cost)}</div>`:""}`;$("upgradeWeapon").hidden=!cost;$("upgradeWeapon").textContent=cost?`장비 +${item.enhanceLevel+1} 강화`:"MAX";$("upgradeWeapon").onclick=upgradeEquipment;$("weaponModal").classList.add("open")}
  function upgradeEquipment(){const item=equipmentById(selectedEquipmentId),cost=equipmentCost(item.enhanceLevel+1);if(!cost)return;if(profile.resources.credits<cost.credits||profile.resources.enhancementShards<cost.enhancementShards)return toast("장비 강화 재화가 부족합니다. (크레딧·무기 모듈 확인)");profile.resources.credits-=cost.credits;profile.resources.enhancementShards-=cost.enhancementShards;item.enhanceLevel++;saveProfile();window.AfterSignalLiveService?.recordEvent?.("characterGrowth",1);render();openEquipment(item.instanceId);toast(`${SHELTER.equipmentCatalog[item.templateId].name} +${item.enhanceLevel}`)}
  function closeEquipment(){$("weaponModal").classList.remove("open")}
  function switchCharacter(step){const ids=unlockedCharacterIds();if(ids.length<2)return;const index=ids.indexOf(selectedCharacterId);selectedCharacterId=ids[(index+step+ids.length)%ids.length];renderDetail()}
  function renderDetailSwitch(){let top=document.querySelector("#detail .detail-top");if(!top){const back=document.querySelector("#detail > .back-main");if(!back)return;top=document.createElement("div");top.className="detail-top";back.before(top);top.append(back);const box=document.createElement("div");box.className="detail-switch";box.innerHTML='<button type="button" data-step="-1" aria-label="이전 대원" title="이전 대원 (←)">‹</button><output></output><button type="button" data-step="1" aria-label="다음 대원" title="다음 대원 (→)">›</button>';top.append(box);box.querySelectorAll("[data-step]").forEach(button=>button.onclick=()=>switchCharacter(Number(button.dataset.step)))}const ids=unlockedCharacterIds();top.querySelector("output").textContent=`${Math.max(1,ids.indexOf(selectedCharacterId)+1)} / ${ids.length}`;top.querySelector(".detail-switch").hidden=ids.length<2}
  function render(){resetStoresIfNeeded();profile.idleRelay.activeHourlyRate=activeHourlyRate();renderTop();renderStoryRoute();renderFacilities();renderOperations();renderShop();renderRoster();if($("detail").classList.contains("active"))renderDetail()}

  recruitEnsure();profile=loadProfile();resetStoresIfNeeded();saveProfile();grantDiamondStarter();
  document.documentElement.classList.toggle("af-embedded",parent!==window);
  document.querySelectorAll(".bottom-nav .nav").forEach((button,index)=>{const icon=button.querySelector("span");if(icon&&NAV_ICONS[button.dataset.nav])icon.innerHTML=NAV_ICONS[button.dataset.nav];if(!button.querySelector("kbd"))button.insertAdjacentHTML("beforeend",`<kbd>${index+1}</kbd>`);button.title=`${button.textContent.replace(/\d$/,"").trim()} (단축키 ${index+1})`});
  document.querySelectorAll("[data-nav]").forEach(button=>button.onclick=()=>showView(button.dataset.nav));
  document.querySelectorAll("[data-home]").forEach(button=>button.onclick=()=>showView("home"));
  document.querySelectorAll("[data-roster]").forEach(button=>button.onclick=()=>showView("roster"));
  document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll(".tab,.tabpane").forEach(node=>node.classList.remove("active"));button.classList.add("active");$(button.dataset.tab).classList.add("active")});
  document.querySelectorAll("[data-shop-tab]").forEach(button=>button.onclick=()=>selectShopTab(button.dataset.shopTab));
  $("continueStory").onclick=event=>{const button=event.currentTarget;if(button.disabled||!button.dataset.screen)return;navigate(button.dataset.screen,button.dataset.standalone)};
  $("returnStory").onclick=$("continueStory").onclick;$("claimIdle").onclick=claimIdle;if($("homeIdleClaim"))$("homeIdleClaim").onclick=claimIdle;setInterval(()=>{if(document.visibilityState==="visible"&&$("home")?.classList.contains("active"))renderIdle()},15000);$("weaponModal").querySelector(".close").onclick=closeEquipment;$("weaponModal").onclick=event=>{if(event.target===$("weaponModal"))closeEquipment()};document.addEventListener("keydown",event=>{if(event.target?.closest?.("input,textarea,select")||$("lockLayer").classList.contains("show"))return;if(event.key==="Escape"){if($("weaponModal").classList.contains("open"))return closeEquipment();const active=document.querySelector(".view.active")?.id;if(active==="detail")return showView("roster");if(active==="extraContentView")return showView("operations");if(active&&active!=="home")return showView("home");return}if(event.ctrlKey||event.metaKey||event.altKey)return;const index="12345".indexOf(event.key);if(index>=0){document.querySelectorAll(".bottom-nav .nav")[index]?.click();return}if($("detail").classList.contains("active")&&(event.key==="ArrowLeft"||event.key==="ArrowRight"))switchCharacter(event.key==="ArrowLeft"?-1:1)});
  if(!PREVIEW_ONLY&&!unlocked())$("lockLayer").classList.add("show");if(!PREVIEW_ONLY)$("previewBadge").hidden=true;
  render();const requestedView=new URLSearchParams(location.search).get("view");if(SHELTER.screens.some(screen=>screen.id===requestedView))showView(requestedView);
  function syncFromFoundation(){profile=loadProfile();render();return profile}
  /* DIAMOND_STARTER_V1 + QUICK_SUPPLY_V1 (2026-09-26): 다이아 = resources.diamonds in the shared profile.
     Rules: AFTERSIGNAL_SHELTER_QUICK_SUPPLY_V1.js + progression/AFTERSIGNAL_DIAMOND_ECONOMY_V1.js. The day follows the
     live-service ResetService (KST, same as the relay contracts); local day only when that service is missing. */
  function grantDiamondStarter(){
    const QS=window.AfterSignalQuickSupply;if(!QS||PREVIEW_ONLY)return false;
    const foundation=readJson(FOUNDATION_KEY);if(!foundation||!QS.grantStarter(foundation))return false;
    localStorage.setItem(FOUNDATION_KEY,JSON.stringify(foundation));profile=loadProfile();saveProfile();return true;
  }
  function quickSupplyDay(time=now()){return window.AfterSignalResetService?.dailyKey?.(time)||localDayKey(new Date(time))}
  function quickSupplyResetInMs(time=now()){return window.AfterSignalResetService?.dailyKey?86400000-(time+9*HOUR)%86400000:nextMidnight()-time}
  function quickSupplyStatus(){const QS=window.AfterSignalQuickSupply;if(!QS)return null;return {...QS.status(profile,{day:quickSupplyDay(),rate:activeHourlyRate()}),resetInMs:quickSupplyResetInMs()}}
  function claimQuickSupply(expectedCost){
    const QS=window.AfterSignalQuickSupply;if(!QS)return {ok:false,reason:"UNAVAILABLE"};
    profile=loadProfile();resetStoresIfNeeded(); // re-read first: another tab's spend or claim is never overwritten
    const result=QS.apply(profile,{day:quickSupplyDay(),rate:activeHourlyRate(),expectedCost});
    if(result.ok){saveProfile();toast(`빠른 보급 ${n(result.granted)} P 수령${result.cost?` · 다이아 ${n(result.cost)} 사용`:""}`)}
    render();return result;
  }
  /* GACHA_RECRUIT_V1 (2026-09-26): 대원 = characters OWNED through recruiting (profile.gacha.owned, written only by
     shared/gacha/AFTERSIGNAL_GACHA_V1.js). Story appearances add no crew; a save without a recruit block (preview, or a
     save the lobby has not migrated) keeps the legacy list. The recruit screen, the home chip and the repeat-operation
     formation are wired by shared/gacha/AFTERSIGNAL_GACHA_LOBBY_V1.js, which calls syncFromFoundation() after each commit
     so this page never writes a stale 다이아 balance back. Stars (한계 돌파) are shown like the other growth numbers. */
  function recruitBlockOf(source){const g=source?.gacha;return g&&typeof g==="object"&&!Array.isArray(g)?g:null}
  function recruitMode(){return Boolean(recruitBlockOf(profile))}
  function recruitEnsure(){if(PREVIEW_ONLY||!window.AfterSignalGacha)return null;try{return window.AfterSignalGacha.createStore({roster:SHELTER.characters,economy:window.AfterSignalDiamondEconomy}).ensure({shelterOpen:true})}catch{return null}}
  function ownedCrewIds(){const G=window.AfterSignalGacha,ids=G?.ownedInOrder?G.ownedInOrder(profile,{roster:SHELTER.characters}):Object.keys(recruitBlockOf(profile)?.owned||{});return ids.filter(id=>SHELTER.characters[id]&&profile.characters[id])}
  function recruitPoolIds(){const G=window.AfterSignalGacha;return G?.buildPool?G.poolIds(G.buildPool(SHELTER.characters)).filter(id=>SHELTER.characters[id]):[]}
  function starsOf(id){const entry=recruitBlockOf(profile)?.owned?.[id];return entry?Math.max(0,Math.min(5,Math.floor(Number(entry.stars)||0))):null}
  function starsHtml(id){const stars=starsOf(id);return stars===null?"":`<span class="crew-stars" data-stars="${stars}" aria-label="한계 돌파 ${stars}단계" title="한계 돌파 ${stars} / 5">${[1,2,3,4,5].map(i=>`<i${i<=stars?' class="on"':""}></i>`).join("")}</span>`}
  /* GROWTH_DISPLAY_V1: combined level + limit-break numbers used in combat (runtime GROWTH_COMBAT_V1). */function combatStatline(id,level){const star=1+.05*(starsOf(id)||0),lv=Math.max(0,(Number(level)||1)-1),atk=(1+.08*lv)*star,guard=(1+.055*lv)*star*star;return `<div class="statline"><span>전투 적용</span><b>공격 ×${atk.toFixed(2)} · 받는 피해 -${Math.round((1-1/guard)*100)}%</b></div>`}function starStatline(id){const stars=starsOf(id);return stars===null?"":`<div class="statline"><span>한계 돌파 ★${stars} / 5</span><b>기본 공격·HP·방어 +${stars*5}%</b></div>`}
  function renderDetailStars(id){const label=document.querySelector("#detail .char-label");if(!label)return;let node=label.querySelector(".detail-stars");const html=starsHtml(id);if(!html){node?.remove();return}if(!node){node=document.createElement("div");node.className="detail-stars";$("detailName").after(node)}node.innerHTML=`${html}<small>한계 돌파 ${starsOf(id)} / 5</small>`}
  function renderRosterTools(recruit,count){const grid=$("rosterGrid");let tools=grid.previousElementSibling?.classList.contains("roster-tools")?grid.previousElementSibling:null;if(!recruit){tools?.remove();return}if(!tools){tools=document.createElement("div");tools.className="roster-tools";grid.before(tools)}const eyebrow=document.querySelector("#roster .section-head .eyebrow");if(eyebrow)eyebrow.textContent="CREW ROSTER";tools.innerHTML=`<p class="rt-count">보유 대원 <b>${count}</b> <span>/ ${recruitPoolIds().length}</span></p><button type="button" class="rt-btn" data-formation-open>출격 편성<small>반복 작전</small></button><button type="button" class="rt-btn rt-recruit" data-recruit-open>대원 모집<small>RECRUIT</small></button>`}
  window.AfterSignalShelterRuntime=Object.freeze({version:"1.1.0",render,quickSupplyStatus,claimQuickSupply,crewIds:()=>unlockedCharacterIds(),recruitMode,syncFromFoundation});
  window.__AFTERSIGNAL_SHELTER_QA__={get profile(){return profile},commanderSupplyBonus,baseHourlyRate,activeHourlyRate,accruedAt,selectShopTab,showView,render,syncFromFoundation};
  addEventListener("pagehide",()=>{clearInterval(idleTicker);clearTimeout(toastTimer)},{once:true});
})();
