(()=>{
  "use strict";
  const screens=[
    {id:"home",label:"대기실",icon:"⌂",kind:"LOBBY"},
    {id:"facility",label:"시설",icon:"⬡",kind:"FACILITY_MAP"},
    {id:"operations",label:"작전",icon:"⌁",kind:"OPERATIONS_HUB"},
    {id:"shop",label:"상점",icon:"◇",kind:"SHOP"},
    {id:"roster",label:"대원",icon:"◉",kind:"ROSTER"}
  ];
  const facilities=[
    {id:"command",name:"지휘 중계실",eyebrow:"COMMAND RELAY",status:"ONLINE",statusKo:"가동 중",x:50,y:44,accent:"cyan",description:"메인 스토리 진행 상황과 다음 작전 경로를 확인합니다."},
    {id:"quarters",name:"대원 숙소",eyebrow:"CREW QUARTERS",status:"3 / 5",x:24,y:31,accent:"violet",description:"합류 대원의 컨디션과 개인 기록을 확인합니다."},
    {id:"workshop",name:"정비 공방",eyebrow:"FIELD WORKSHOP",status:"READY",statusKo:"사용 가능",x:73,y:29,accent:"amber",description:"고유 무기와 4종 장비 모듈을 강화합니다."},
    {id:"archive",name:"신호 보관고",eyebrow:"SIGNAL ARCHIVE",status:"SYNC 72%",statusKo:"동기화 72% · 준비 중",x:25,y:70,accent:"cyan",description:"회수한 기억 파편·전투 로그·음성 기록을 보존합니다."},
    {id:"supply",name:"릴레이 보급소",eyebrow:"RELAY SUPPLY",status:"120 / H",x:75,y:69,accent:"amber",description:"시간 누적 보급을 수령하고 일간·주간 재고를 교환합니다."}
  ];
  const operations=[
    {id:"story",name:"현장 기록",eyebrow:"MAIN SIGNAL",tag:"STORY",state:"AVAILABLE",description:"메인 스토리와 전투를 이어갑니다.",tone:"cyan"},
    {id:"signalSweep",name:"신호 소탕전",eyebrow:"DAILY SWEEP",tag:"DAILY",state:"AVAILABLE",description:"매일 구성이 바뀌는 3파동 변주 전투입니다.",tone:"cyan"},
    {id:"tacticalSimulation",name:"전술 시뮬레이션",eyebrow:"WEEKLY SCORE",tag:"WEEKLY",state:"AVAILABLE",description:"매주 바뀌는 전투 변수 속에서 최고 점수에 도전합니다.",tone:"blue"},
    {id:"threatInterception",name:"위협체 요격",eyebrow:"CERTIFIED BOSS",tag:"BOSS",state:"AVAILABLE",description:"주 1회 실전 인증 후 빠른 전투를 사용할 수 있습니다.",tone:"red"},
    {id:"noSignalZone",name:"무신호 구역",eyebrow:"WEEKLY SECTOR",tag:"EXPEDITION",state:"AVAILABLE",description:"매주 바뀌는 탐사 노드를 차례로 돌파합니다.",tone:"violet"},
    {id:"relayTower",name:"릴레이 타워",eyebrow:"PERMANENT",tag:"FIRST CLEAR",state:"AVAILABLE",description:"초기화 없이 한 층씩 올라가는 영구 도전 전선입니다.",tone:"amber"}
  ];
  const characters={
    mira:{id:"mira",characterId:"SSR-01",name:"미라 보스",title:"LUMEN FIELD LINK",rarity:"SSR",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/mira/standing_2026_09_23/MIRA_VOSS_STANDING_FRESH_A001.png",portrait:"../assets/final_2p5d_v066/portraits/MIRA_HUD_2026_09_23.webp",weapon:{id:"WPN-SSR-01-R0_RELAY_CARBINE",name:"R-0 릴레이 카빈",magazine:12,damage:168},skills:{passive:["P","신호 규율"],skill1:["1","교정 핑"],skill2:["2","화이트 릴레이"],ultimate:["E","고요한 지평선"]}},
    haneul:{id:"haneul",characterId:"SSR-02",name:"하늘-7",title:"SECOND CHANNEL",rarity:"SSR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"SUPPORT",typeKo:"지원형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/haneul/standing_2026_09_30/HANEUL_STANDING_A005.png",portrait:"../assets/final_2p5d_v066/portraits/HANEUL_HUD_2026_09_30.webp",weapon:{id:"WPN-SSR-02-HUSH_SEEKER",name:"하늘-7 허시 시커",magazine:18,damage:62},skills:{passive:["P","무음 관측"],skill1:["1","오염 분리"],skill2:["2","보호 채널"],ultimate:["E","제로 컨테미네이션"]}},
    sera:{id:"sera",characterId:"SSR-07",name:"세라 플린트",title:"ANALOG BREACH",rarity:"SSR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"COMBAT",typeKo:"전투형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/sera/standing_2026_09_23/SERA_FLINT_STANDING_NORM_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SERA_HUD_2026_09_23.webp",weapon:{id:"WPN-SSR-07-ANALOG_HUNTER",name:"플린트 아날로그 헌터",magazine:8,damage:154},skills:{passive:["P","아날로그 감각"],skill1:["1","아날로그 점화"],skill2:["2","플레어 파열"],ultimate:["E","아날로그 플레어"]}},
    astra:{id:"astra",characterId:"SSR-11",name:"아스트라 벨",title:"AFTERGLOW VECTOR",rarity:"SSR",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/astra/standing_2026_09_23/ASTRA_BELL_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/ASTRA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-11-AFTERGLOW_VECTOR",name:"애프터글로 벡터 라이플",magazine:12,damage:148},skills:{passive:["P","고정 축선"],skill1:["1","벡터 교정"],skill2:["2","엄폐 반전"],ultimate:["E","애프터글로 벡터"]}},
    tessa:{id:"tessa",characterId:"SSR-04",name:"테사 룬",title:"FOUNDRY HEAVY",rarity:"SSR",faction:"FRAME_INDUSTRIAL",factionKo:"프레임 공업국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/tessa/standing_2026_09_23/TESSA_RUNE_STANDING_A002.png",portrait:"../assets/final_2p5d_v066/portraits/TESSA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-04-FOUNDRY_HEAVY",name:"파운드리 헤비",magazine:10,damage:150},skills:{passive:["P","수리 불가 인격"],skill1:["1","중장 교정"],skill2:["2","엄폐 복구"],ultimate:["E","파운드리 가드"]}},
    naru:{id:"naru",characterId:"SSR-05",name:"나루 세이건",title:"CONTINUITY MEDIC",rarity:"SSR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/naru/standing_2026_09_23/NARU_SEIGAN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/NARU_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-05-THREAD_PROJECTOR",name:"실 프로젝터",magazine:14,damage:132},skills:{passive:["P","생존 연속성"],skill1:["1","동결 표식"],skill2:["2","복원 해제"],ultimate:["E","연속성 필드"]}},
    karin:{id:"karin",characterId:"SSR-13",name:"카린 베가",title:"IRON REARGUARD",rarity:"SSR",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/karin/standing_2026_09_23/KARIN_VEGA_STANDING_A002.png",portrait:"../assets/final_2p5d_v066/portraits/KARIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-13-VEGA_FOUNDRY_HEAVY",name:"베가 파운드리 헤비",magazine:4,damage:228},skills:{passive:["P","후방 방벽"],skill1:["1","파운드리 중탄"],skill2:["2","회수 엄호"],ultimate:["E","철벽 포격"]}},
    serin:{id:"serin",characterId:"SR-02",name:"세린",title:"TRIANGULATION",rarity:"SR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/serin/standing_2026_09_23/SERIN_STANDING_SHORTS_A002.png",portrait:"../assets/final_2p5d_v066/portraits/SERIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-02-SEAL_PROJECTOR",name:"세린 실 프로젝터",magazine:15,damage:96},skills:{passive:["P","오차 보정"],skill1:["1","교차 사선"],skill2:["2","외곽 봉인선"],ultimate:["E","삼각 봉인"]}},
    luna:{id:"luna",characterId:"SR-13",name:"루나",title:"FOUNDRY WALL",rarity:"SR",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/luna/standing_2026_09_23/LUNA_STANDING_A003.png",portrait:"../assets/final_2p5d_v066/portraits/LUNA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-13-LUNA_FOUNDRY_WALL",name:"루나 파운드리 월",magazine:31,damage:116},skills:{passive:["P","방벽 유지"],skill1:["1","회전 제압"],skill2:["2","엄폐 보강"],ultimate:["E","파운드리 월"]}},
    arin:{id:"arin",characterId:"SR-10",name:"아린",title:"OPEN FORMULA",rarity:"SR",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/arin/standing_2026_09_23/ARIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/ARIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-10-ARIN_MODULAR_DRONE",name:"아린 모듈러 드론",magazine:27,damage:108},skills:{passive:["P","변수 검증"],skill1:["1","주석 카드"],skill2:["2","반례 제시"],ultimate:["E","공개 판단식"]}},
    jaein:{id:"jaein",characterId:"SSR-08",name:"재인 복스",title:"OFFBEAT CHORUS",rarity:"SSR",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/jaein/standing_2026_09_23/JAEIN_VOX_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/JAEIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-08-VOX_MODULAR_DRONE",name:"복스 모듈러 드론",magazine:12,damage:112},skills:{passive:["P","엇박 동기화"],skill1:["1","스타카토 드론"],skill2:["2","쉼표 방벽"],ultimate:["E","복스 합창"]}},
    roa:{id:"roa",characterId:"SR-03",name:"로아",title:"FULL TORQUE",rarity:"SR",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/roa/standing_2026_09_23/ROA_STANDING_A002.png",portrait:"../assets/final_2p5d_v066/portraits/ROA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-03-FORGE_OVERDRIVE",name:"로아 포지 오버드라이브",magazine:17,damage:142},skills:{passive:["P","코일 예열"],skill1:["1","과열 볼트"],skill2:["2","현장 용접"],ultimate:["E","포지 오버드라이브"]}},
    noella:{id:"noella",characterId:"SSR-12",name:"노엘라 크로스",title:"WITNESS KEEPER",rarity:"SSR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/noella/standing_2026_09_23/NOELLA_CROSS_STANDING_A002.png",portrait:"../assets/final_2p5d_v066/portraits/NOELLA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-12-CROSS_SEAL_PROJECTOR",name:"크로스 실 프로젝터",magazine:11,damage:124},skills:{passive:["P","남겨진 증언"],skill1:["1","십자 봉인탄"],skill2:["2","고백 청취"],ultimate:["E","증언의 봉인"]}},
    ria:{id:"ria",characterId:"SR-04",name:"리아",title:"SPEARHEAD",rarity:"SR",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/ria/standing_2026_09_23/RIA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/RIA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-04-VANGUARD_PULSE",name:"리아 뱅가드 펄스",magazine:19,damage:148},skills:{passive:["P","돌파 선봉"],skill1:["1","펄스 랜스"],skill2:["2","중앙 개방"],ultimate:["E","직선 돌파"]}},
    bomin:{id:"bomin",characterId:"R-02",name:"보민",title:"ZERO MISFIRE",rarity:"R",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/bomin/standing_2026_09_23/BOMIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/BOMIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-02-VANGUARD_RAIL",name:"보민 뱅가드 레일",magazine:35,damage:87},skills:{passive:["P","한 발의 계산"],skill1:["1","관통 정밀탄"],skill2:["2","사격선 유지"],ultimate:["E","앰버 라인"]}},
    orin:{id:"orin",characterId:"SSR-03",name:"오린 베일",title:"STAY OF EXECUTION",rarity:"SSR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/orin/standing_2026_09_23/ORIN_VALE_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/ORIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-03-VALE_ADJUDICATOR",name:"베일 어드주디케이터",magazine:14,damage:192},skills:{passive:["P","판결 유예"],skill1:["1","증거 채택"],skill2:["2","효력 정지"],ultimate:["E","집행 인장"]}},
    yunseo:{id:"yunseo",characterId:"R-10",name:"윤서",title:"LAST CHECKSUM",rarity:"R",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/yunseo/standing_2026_09_23/YUNSEO_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YUNSEO_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-10-SEAL_PROJECTOR",name:"윤서 실 프로젝터",magazine:43,damage:76},skills:{passive:["P","출처 유지"],skill1:["1","판정 표식"],skill2:["2","병렬 보존"],ultimate:["E","교차 검증선"]}},
    yura:{id:"yura",characterId:"R-05",name:"유라",title:"FIELD CARTOGRAPHER",rarity:"R",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/yura/standing_2026_09_23/YURA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YURA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-05-FIELD_SEEKER",name:"유라 필드 시커",magazine:38,damage:74},skills:{passive:["P","현재 흔적"],skill1:["1","우회로 표시"],skill2:["2","표식 유도"],ultimate:["E","등고선 측량"]}},
    yeonhwa:{id:"yeonhwa",characterId:"R-07",name:"연화",title:"CHANNEL WARDEN",rarity:"R",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/yeonhwa/standing_2026_09_23/YEONHWA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YEONHWA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-07-ANCHOR_PLATE",name:"연화 앵커 플레이트",magazine:40,damage:80},skills:{passive:["P","철수권 잠금"],skill1:["1","채널 분리"],skill2:["2","퇴로 개방"],ultimate:["E","귀환선"]}},
    narae:{id:"narae",characterId:"SR-05",name:"나래",title:"RAILYARD HUNTER",rarity:"SR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/narae/standing_2026_09_23/NARAE_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/NARAE_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-05-ANALOG_HUNTER",name:"나래 아날로그 헌터",magazine:21,damage:118},skills:{passive:["P","사선 확보"],skill1:["1","제압 연사"],skill2:["2","연결부 사수"],ultimate:["E","마지막 탄"]}},
    moa:{id:"moa",characterId:"SR-08",name:"모아",title:"ANCHOR BASTION",rarity:"SR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/moa/standing_2026_09_23/MOA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/MOA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-08-ANCHOR_PLATE",name:"모아 앵커 플레이트",magazine:25,damage:92},skills:{passive:["P","전열고정"],skill1:["1","방벽전개"],skill2:["2","사선봉쇄"],ultimate:["E","쌍선 봉쇄"]}},
    yumi:{id:"yumi",characterId:"SR-09",name:"유미",title:"DUAL LINE WARDEN",rarity:"SR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/yumi/standing_2026_09_23/YUMI_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YUMI_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-09-ADJUDICATOR_NEEDLE",name:"유미 어드주디케이터",magazine:26,damage:138},skills:{passive:["P","집행 정지"],skill1:["1","심박선 분리"],skill2:["2","철수선 보장"],ultimate:["E","쌍방 보호선"]}},
    sion:{id:"sion",characterId:"R-03",name:"시온",title:"PRESS LINE BREAKER",rarity:"R",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/sion/standing_2026_09_23/SION_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SION_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-03-FORGE_OVERDRIVE",name:"시온 포지 브레이커",magazine:36,damage:94},skills:{passive:["P","과열 한계 91"],skill1:["1","역순 정지"],skill2:["2","코어 분리 사격"],ultimate:["E","세 갈래 절단"]}},
    haejin:{id:"haejin",characterId:"R-01",name:"해진",title:"FOUNDRY KEEPER",rarity:"R",faction:"FRAME_INDUSTRY",factionKo:"프레임 공업국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/haejin/standing_2026_09_23/HAEJIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/HAEJIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-01-FOUNDRY_HEAVY",name:"해진 파운드리 플레이트",magazine:34,damage:86},skills:{passive:["P","잔향 보존"],skill1:["1","설비 엄호"],skill2:["2","분리 방벽"],ultimate:["E","독립 방벽 세 겹"]}},
    eve:{id:"eve",characterId:"SSR-10",name:"이브 녹턴",title:"SHADOW LINE CUTTER",rarity:"SSR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/eve/standing_2026_09_23/EVE_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/EVE_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-10-HARMONIC_BEAM",name:"녹턴 하모닉 윙",magazine:18,damage:186},skills:{passive:["P","잔광 차단"],skill1:["1","그림자 우회"],skill2:["2","날개 안테나"],ultimate:["E","암흑 우회선"]}},
    sea:{id:"sea",characterId:"R-06",name:"세아",title:"PULSE DIVIDER",rarity:"R",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/sea/standing_2026_09_23/SEA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SEA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-06-CHOIR_EMITTER",name:"세아 콰이어 펄스",magazine:39,damage:88},skills:{passive:["P","손 든 신호"],skill1:["1","뿌리 분리선"],skill2:["2","오른쪽 출구"],ultimate:["E","다섯 맥, 같은 순간"]}},
    seorin:{id:"seorin",characterId:"SR-06",name:"서린",title:"CHANNEL MEDIUM",rarity:"SR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/seorin/standing_2026_09_23/SEORIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SEORIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-06-CHOIR_EMITTER",name:"서린 콰이어 이미터",magazine:22,damage:104},skills:{passive:["P","철회 채널"],skill1:["1","기억 겹치기"],skill2:["2","같은 원"],ultimate:["E","세 갈래 공명"]}},
    lumi:{id:"lumi",characterId:"SR-07",name:"루미",title:"SOLO CHANNEL ANCHOR",rarity:"SR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/lumi/standing_2026_09_23/LUMI_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/LUMI_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-07-PHASE_ANCHOR",name:"루미 페이즈 앵커",magazine:23,damage:110},skills:{passive:["P","솔로 채널"],skill1:["1","세 박자 공개"],skill2:["2","두 박자 격리"],ultimate:["E","다섯 트랙 동시 재생"]}},
    iona:{id:"iona",characterId:"SSR-06",name:"이오나 렉스",title:"LEDGER BREAKER",rarity:"SSR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/iona/standing_2026_09_23/IONA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/IONA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-06-HARMONIC_BEAM",name:"렉스 하모닉 엣지",magazine:12,damage:215},skills:{passive:["P","내 이름의 선택"],skill1:["1","표적판 쪼개기"],skill2:["2","전방 개방"],ultimate:["E","크림슨 버딕트"]}},
    somi:{id:"somi",characterId:"R-04",name:"소미",title:"ROTARY WARDEN",rarity:"R",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/somi/standing_2026_09_23/SOMI_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SOMI_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-04-BASTION_ROTARY",name:"소미 바스티온 로터리",magazine:37,damage:78},skills:{passive:["P","연속 중계"],skill1:["1","포열 가동"],skill2:["2","수신점 봉쇄"],ultimate:["E","끊기지 않은 답신"]}},
    mei:{id:"mei",characterId:"SR-15",name:"메이",title:"BEDSIDE KEEPER",rarity:"SR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/mei/standing_2026_09_23/MEI_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/MEI_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-15-FIELD_SURVEYOR",name:"메이 필드 서베이어",magazine:33,damage:98},skills:{passive:["P","손글씨 동의서"],skill1:["1","환자 이름표"],skill2:["2","머리맡 경계"],ultimate:["E","깨어나실 때까지"]}},
    yuria:{id:"yuria",characterId:"SSR-14",name:"유리아 글린트",title:"ON AIR COUNTER",rarity:"SSR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/yuria/standing_2026_09_23/YURIA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YURIA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-14-HARMONIC_BEAM",name:"글린트 하모닉 트윈",magazine:30,damage:48},skills:{passive:["P","계속 세기"],skill1:["1","박자 유지"],skill2:["2","호흡 트랙"],ultimate:["E","하나 둘 셋 지금"]}},
    soha:{id:"soha",characterId:"SR-14",name:"소하",title:"BLINDSPOT SCOUT",rarity:"SR",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/soha/standing_2026_09_23/SOHA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/SOHA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-14-HARMONIC_BEAM",name:"소하 하모닉 라이플",magazine:32,damage:134},skills:{passive:["P","늦은 관측"],skill1:["1","사각 조준"],skill2:["2","숨은 진입로"],ultimate:["E","누락된 세 번째 길"]}},
    liora:{id:"liora",characterId:"SSR-09",name:"리오라 크레스트",title:"CUSTODY VANGUARD",rarity:"SSR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/liora/standing_2026_09_23/LIORA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/LIORA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-09-CUSTODY_BREACH",name:"크레스트 커스터디",magazine:9,damage:198},skills:{passive:["P","호송 서약"],skill1:["1","인장 방벽"],skill2:["2","새 서약"],ultimate:["E","서약의 창끝"]}},
    bella:{id:"bella",characterId:"SSR-15",name:"벨라 루멘",title:"TRIAGE WARDEN",rarity:"SSR",faction:"SILENT_COMMUNE",factionKo:"무음 공동체",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/bella/standing_2026_09_23/BELLA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/BELLA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SSR-15-FIELD_SURVEYOR",name:"루멘 필드 서베이어",magazine:24,damage:68},skills:{passive:["P","환자 분류"],skill1:["1","루멘 방호"],skill2:["2","지연 표식"],ultimate:["E","응급 이송선"]}},
    dana:{id:"dana",characterId:"SR-11",name:"다나",title:"IMPACT OBSERVER",rarity:"SR",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"COMBAT",typeKo:"전투형",formation:"중열",standing:"../assets/final_2p5d_v066/characters/dana/standing_2026_09_23/DANA_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/DANA_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-11-VANGUARD_PULSE",name:"다나 뱅가드 카빈",magazine:28,damage:152},skills:{passive:["P","현재 시각 기록"],skill1:["1","탄흔 좌표"],skill2:["2","기록 정정"],ultimate:["E","현재 시각의 좌표"]}},
    chaerin:{id:"chaerin",characterId:"SR-12",name:"채린",title:"RETREAT ROUTE CLERK",rarity:"SR",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"SUPPORT",typeKo:"지원형",formation:"후열",standing:"../assets/final_2p5d_v066/characters/chaerin/standing_2026_09_23/CHAERIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/CHAERIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-12-SEAL_PROJECTOR",name:"채린 실 포인터",magazine:29,damage:101},skills:{passive:["P","퇴로 확보"],skill1:["1","케이블 표식"],skill2:["2","하나면 충분"],ultimate:["E","남은 길 개통"]}},
    yujin:{id:"yujin",characterId:"SR-01",name:"유진",title:"CORRIDOR WARDEN",rarity:"SR",faction:"RELAY_UNION",factionKo:"릴레이 연합",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/yujin/standing_2026_09_23/YUJIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/YUJIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-SR-01-BASTION_ROTARY",name:"유진 바스티온 리피터",magazine:13,damage:106},skills:{passive:["P","거동 불가자부터"],skill1:["1","추락 예상선"],skill2:["2","들것 스물"],ultimate:["E","착륙 회랑"]}},
    harin:{id:"harin",characterId:"R-08",name:"하린",title:"CUSTODY ARCHIVIST",rarity:"R",faction:"CONTINUITY_BUREAU",factionKo:"연속성 관리국",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/harin/standing_2026_09_23/HARIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/HARIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-08-CUSTODY_BREACH",name:"하린 커스터디 브리치",magazine:41,damage:84},skills:{passive:["P","보류 등록"],skill1:["1","보호 조건"],skill2:["2","효력 정지"],ultimate:["E","아흔세 칸"]}},
    dabin:{id:"dabin",characterId:"R-09",name:"다빈",title:"REFUGE VANGUARD",rarity:"R",faction:"RESONANCE_WAVE",factionKo:"공명파",type:"DEFENSE",typeKo:"방어형",formation:"전열",standing:"../assets/final_2p5d_v066/characters/dabin/standing_2026_09_23/DABIN_STANDING_A001.png",portrait:"../assets/final_2p5d_v066/portraits/DABIN_HUD_2026_09_23.webp",presentationPolicy:"MODULAR_BAKE_V1_ENGINEERING",weapon:{id:"WPN-R-09-PHASE_ANCHOR",name:"다빈 페이즈 앵커",magazine:42,damage:90},skills:{passive:["P","민간 참호"],skill1:["1","선행 돌입"],skill2:["2","이송로 확보"],ultimate:["E","끝까지 열린 이송로"]}}
  };
  const shopStock=[
    {id:"battle_data_1000",name:"전투 기록 ×1,000",category:"CHARACTER",period:"daily",stock:3,price:1500,icon:"▰",desc:"선택한 대원의 개별 레벨업에 사용합니다.",grant:{battleData:1000}},
    {id:"enhancement_shard_4",name:"무기 모듈 ×4",category:"EQUIPMENT",period:"daily",stock:3,price:1800,icon:"⬡",desc:"장비 모듈을 +0~+5까지 강화하는 재료입니다.",grant:{enhancementShards:4}},
    {id:"skill_manual_3",name:"스킬 매뉴얼 ×3",category:"SKILL",period:"daily",stock:2,price:2200,icon:"✦",desc:"일반 스킬과 필살기 레벨업 자료입니다.",grant:{skillManual:3}},
    {id:"faction_type_equipment_box",name:"진영·타입 장비 상자",category:"EQUIPMENT",period:"weekly",stock:1,price:3600,icon:"◇",desc:"현재 진행도에 맞는 +0 장비 모듈 1개를 획득합니다.",grant:{equipmentBox:1}}
  ];
  const idleExchange=[
    {id:"idle_supply_credits_1000",name:"크레딧 ×1,000",period:"daily",baseStock:5,cost:1000,icon:"G",grant:{credits:1000}},
    {id:"idle_supply_battle_data_500",name:"전투 기록 ×500",period:"daily",baseStock:4,cost:750,icon:"▰",grant:{battleData:500}},
    {id:"idle_supply_shard_1",name:"무기 모듈 ×1",period:"weekly",baseStock:8,cost:900,icon:"⬡",grant:{enhancementShards:1}}
  ];
  const idleSupplyPolicy=Object.freeze({
    baseHourlyRate:120,
    perCommanderLevelHourlyIncrease:2,
    bossClearHourlyIncrease:8,
    bossClearCap:15,
    commanderTierFirstLevel:21,
    commanderTierInterval:20,
    commanderTierBonusRate:.03,
    maximumAccrualHours:72
  });
  const equipmentSlots=[
    {id:"FRAME_MODULE",name:"프레임 모듈",hint:"생존·기초 프레임"},
    {id:"SIGNAL_MODULE",name:"신호 모듈",hint:"스킬·신호 회전"},
    {id:"TACTICAL_MODULE",name:"전술 모듈",hint:"공격·코어·장탄"},
    {id:"PROTECTION_MODULE",name:"방호 모듈",hint:"방어·엄폐·보호막"}
  ];
  const equipmentCatalog={
    "EQ-RU-S-01":{templateId:"EQ-RU-S-01",name:"릴레이 컨덕터",faction:"RELAY_UNION",type:"SUPPORT",stat:"스킬 회복 +1.0%"},
    "EQ-SC-S-01":{templateId:"EQ-SC-S-01",name:"허시 드론 허브",faction:"SILENT_COMMUNE",type:"SUPPORT",stat:"상태 저항 +2.0%"},
    "EQ-SC-C-01":{templateId:"EQ-SC-C-01",name:"위스퍼 카빈",faction:"SILENT_COMMUNE",type:"COMBAT",stat:"일반 공격 +1.5%"},
    "EQ-RU-C-01":{templateId:"EQ-RU-C-01",name:"벡터드 레일",faction:"RELAY_UNION",type:"COMBAT",stat:"명중 안정 +1.5%"}
  };
  const labels=Object.freeze({codes:Object.freeze({RELAY_UNION:"릴레이 연합",SILENT_COMMUNE:"무음 공동체",FRAME_INDUSTRIAL:"프레임 공업국",FRAME_INDUSTRY:"프레임 공업국",CONTINUITY_BUREAU:"연속성 관리국",SUPPORT:"지원형",COMBAT:"전투형",DEFENSE:"방어형"})});
  const assetPolicy=Object.freeze({storyAndBase:"STANDING_ONLY",combat:"SEATED_REAR_ONLY",standingInCombat:false,seatedInShelter:false});
  window.AfterSignalShelter=Object.freeze({version:"2.0.0",maxPartySize:5,screens,facilities,operations,characters,shopStock,idleExchange,idleSupplyPolicy,equipmentSlots,equipmentCatalog,assetPolicy,labels});
})();
