/* Data-driven screen/stage flow. No stage count or numeric adjacency assumptions. */
(()=>{
  "use strict";
  // Story pages share one character-slot contract. Injecting the stylesheet
  // here keeps direct pages and generated single-file screens on the same rule.
  // The shell (index.html) loads this file as "shared/..." and has no story screen; the relative stylesheet path
  // below only resolves from pages/, so the shell skips it (it used to request a missing ../shared path, 2026-09-26).
  const flowScript=typeof document!=="undefined"?document.currentScript:null,flowSrc=(flowScript&&typeof flowScript.getAttribute==="function"&&flowScript.getAttribute("src"))||"";
  if(typeof document!=="undefined"&&!/^(?:\.\/)?shared\//.test(flowSrc)&&!document.querySelector('link[data-af-story-placement="v1"]')){
    const placement=document.createElement("link");placement.rel="stylesheet";placement.href="../shared/story-ui/AFTERSIGNAL_STORY_CONTROLS_GLOBAL.css";placement.dataset.afStoryPlacement="v1";document.head.append(placement);
  }
  const freeze=value=>Object.freeze(value),PENDING_KEY="aftersignal:pending-reward:v3";
  const rows=[
    {stageId:"P-01",stageType:"STORY_COMBAT",entry:"prologue",combat:"combat",reward:"reward",after:"postbattle",nextStage:"P-02",rewardSpec:{title:"차가운 기동",rank:"B",credits:2200,commanderXp:90,battleData:600,coreSignal:0,weaponModules:2}},
    {stageId:"P-02",stageType:"STORY_COMBAT",entry:"p02",combat:"p02combat",reward:"reward",after:"p03",nextStage:"P-03",rewardSpec:{title:"끊어진 제어선",rank:"B",credits:3000,commanderXp:120,battleData:900,coreSignal:1,weaponModules:3}},
    {stageId:"P-03",stageType:"STORY",entry:"p03",combat:null,reward:null,after:"p04",nextStage:"P-04",rewardSpec:null},
    {stageId:"P-04",stageType:"STORY_COMBAT",entry:"p04",combat:"p04combat",reward:"reward",after:"prologueContinue",nextStage:"P-05",rewardSpec:{title:"남겨진 발자국",rank:"A",credits:4800,commanderXp:180,battleData:1600,coreSignal:2,weaponModules:8,weapon:{id:"relay_carbine_r0",name:"R-0 릴레이 카빈",rarity:"SR",faction:"LUMEN",role:"지원형",weaponClass:"정밀소총",level:1,xp:0,equippedBy:null}}},
    {stageId:"P-05",stageType:"STORY",entry:"prologueContinue",combat:null,reward:null,after:"p06combat",nextStage:"P-06",rewardSpec:null},
    {stageId:"P-06",stageType:"COMBAT",entry:"p06combat",combat:"p06combat",reward:"reward",after:"p07intro",nextStage:"P-07",rewardSpec:{title:"잠긴 정비선",rank:"A",credits:5600,commanderXp:210,battleData:1900,coreSignal:2,weaponModules:9}},
    {stageId:"P-07",stageType:"MIDBOSS",entry:"p07intro",combat:"p07combat",reward:"reward",after:"p07outro",nextStage:"P-08",rewardSpec:{title:"무신호 감시자",rank:"S",credits:7800,commanderXp:300,battleData:2800,coreSignal:4,weaponModules:12}},
    {stageId:"P-08",stageType:"STORY_COMBAT",entry:"p08intro",combat:"p08combat",reward:"reward",after:"p08outro",nextStage:"P-09",rewardSpec:{title:"권한 로그 회수",rank:"A",credits:6500,commanderXp:240,battleData:2300,coreSignal:3,weaponModules:10}},
    {stageId:"P-09",stageType:"STORY_COMBAT",entry:"p09intro",combat:"p09combat",reward:"reward",after:"p14intro",nextStage:"P-14",rewardSpec:{title:"아날로그 불꽃",rank:"S",credits:9200,commanderXp:360,battleData:3400,coreSignal:5,weaponModules:14}},
    {stageId:"P-14",stageType:"MIDBOSS",entry:"p14intro",combat:"p14combat",reward:"reward",after:"p14outro",nextStage:"TEMPORARY-BASE",rewardSpec:{title:"미라의 목소리를 가진 것",rank:"S",credits:11200,commanderXp:460,battleData:4200,coreSignal:7,weaponModules:18}}
  ].map(row=>freeze({...row,rewardSpec:row.rewardSpec?freeze({stageId:row.stageId,next:row.after,...row.rewardSpec}):null}));
  const byStage=new Map(rows.map(row=>[row.stageId,row])),byScreen=new Map();
  for(const row of rows)for(const [phase,screen] of [["entry",row.entry],["combat",row.combat],["after",row.after]])if(screen&&screen!=="reward")byScreen.set(screen,freeze({stageId:row.stageId,phase,screen}));
  byScreen.set("title",freeze({stageId:null,phase:"boot",screen:"title"}));byScreen.set("lobby",freeze({stageId:"TEMPORARY-BASE",phase:"base",screen:"lobby"}));
  const normalizeStage=value=>{const raw=String(value||"").toUpperCase();return raw.replace(/^P(\d+)$/,(_,digits)=>`P-${digits.padStart(2,"0")}`)};
  const routeForStage=stageId=>byStage.get(normalizeStage(stageId))||null;
  const routeForScreen=screen=>byScreen.get(String(screen||""))||null;
  const nextScreen=(screen,{stageId=null}={})=>{const current=String(screen||"");if(current==="title")return"prologue";if(current==="reward")return routeForStage(stageId)?.after||null;const hit=routeForScreen(current),route=hit?routeForStage(hit.stageId):null;if(!hit||!route)return null;if(hit.phase==="entry")return route.combat||route.after;if(hit.phase==="combat")return route.reward;if(hit.phase==="after")return route.nextStage==="TEMPORARY-BASE"?"lobby":routeForStage(route.nextStage)?.entry||null;return null};
  const queueBattleCompletion=({stageId,transactionId=null}={})=>{const route=routeForStage(stageId);if(!route?.combat||!route.rewardSpec)throw new Error(`No combat route for ${stageId}`);const token=String(transactionId||`${route.stageId}:${Date.now().toString(36)}`),stage=route.stageId.toLowerCase().replace("-","");let current=null;try{current=JSON.parse(localStorage.getItem(PENDING_KEY)||"null")}catch{}if(current?.token===token)return current;const pending={stage,next:route.after,afterScreen:route.after,nextStage:route.nextStage,token,createdAt:Date.now()};localStorage.setItem(PENDING_KEY,JSON.stringify(pending));return pending};
  const dispatchNavigation=screen=>{if(!screen)throw new Error("Stage flow has no released next screen");if(parent!==window)parent.postMessage({type:"aftersignal:navigate",screen},"*");else location.href=`${screen}.html`;return screen};
  const completeBattle=detail=>{const pending=queueBattleCompletion(detail);if(parent!==window)parent.postMessage({type:"aftersignal:battle-complete",...pending,next:"reward"},"*");else location.href="reward.html";return pending};
  const continueFrom=(screen,options={})=>dispatchNavigation(nextScreen(screen,options));
  const STORY_SLOT_X=freeze({1:[73],2:[27,73],3:[16,50,84],4:[11,37,63,89],5:[8,29,50,71,92]});
  const STORY_MIXED_SLOT_X=freeze({2:[24,76],3:[14,50,84],4:[8,34,60,86],5:[6,26,46,66,86]});
  const STORY_MIXED_PORTRAIT_SLOT_X=freeze({2:[25,75],3:[16,50,84],4:[12,36,60,84],5:[10,30,50,70,90]});
  // Story actor layout V2 (2026-09-26): a solo portrait speaker is centred; portrait groups are pulled in from the phone edge.
  const STORY_PORTRAIT_SLOT_X=freeze({1:[50],2:[30,70],3:[20,50,80],4:[14,38,62,86],5:[10,30,50,70,90]});
  // Alpha bounding boxes measured on the story standing PNGs, as fractions of the image: t=head top, b=boot sole,
  // cx=body centre, wf=body width per image width (Sera without her staff). h=drawn body height relative to Mira.
  const STORY_ACTOR_BODY=freeze({mira:freeze({t:.005,b:.995,cx:.558,wf:.594,h:1}),haneul:freeze({t:.016,b:.984,cx:.5,wf:.46,h:.92}),sera:freeze({t:.077,b:.896,cx:.473,wf:.62,h:.95}),other:freeze({t:0,b:1,cx:.5,wf:.6,h:1})});
  // Stable sides inside a page: Haneul and Sera stay left of Mira, who keeps the canonical right slot of the story CSS contract.
  const STORY_ACTOR_ORDER=freeze(["haneul","sera","other","mira"]);
  const STORY_SPEAKER_ACTOR=freeze([["미라 보스","mira"],["하늘","haneul"],["세라","sera"]]);
  // Haneul's standing art is only 512x512: never draw it above 1.4x its pixel height (the pre-V2 maximum).
  const STORY_MAX_ART_UPSCALE=1.4;
  let actorLayoutQueued=false;
  const storyActorKey=node=>{const key=`${node.id||""} ${node.getAttribute("src")||""}`.toLowerCase();return key.includes("haneul")?"haneul":key.includes("sera")?"sera":key.includes("mira")?"mira":"other";};
  const layoutStoryActors=()=>{
    actorLayoutQueued=false;
    const visible=node=>{const style=getComputedStyle(node);return style.display!=="none"&&style.visibility!=="hidden";},legacyOperator=[...document.querySelectorAll("img.operator")].filter(node=>{const host=node.closest("[data-speaker],[data-mode]")||node.parentElement,mode=String(host?.dataset.speaker||host?.dataset.mode||"");return mode.includes("mira")&&host?.dataset.encounter!=="true";}),legacyListener=[...document.querySelectorAll("img.operator")].filter(node=>!legacyOperator.includes(node)&&(node.closest("[data-speaker],[data-mode]")||node.parentElement)?.dataset.encounter!=="true"&&parseFloat(getComputedStyle(node).opacity)>.05),actors=[...document.querySelectorAll(".actor.show"),...document.querySelectorAll(".actor.dim:not(.show)"),...legacyOperator,...legacyListener].filter(visible).sort((a,b)=>STORY_ACTOR_ORDER.indexOf(storyActorKey(a))-STORY_ACTOR_ORDER.indexOf(storyActorKey(b))),threats=[...document.querySelectorAll(".warden.show,.echo.show,.enemy.show")].filter(visible),entities=[...actors,...threats].slice(0,5),count=entities.length;if(!count)return;
    const portrait=matchMedia("(orientation:portrait)").matches,mixed=threats.length>0,actorHeights=portrait?(mixed?{1:66,2:64,3:58,4:52,5:46}:{1:89,2:81,3:73,4:65,5:58}):(mixed?{1:62,2:62,3:62,4:52,5:46}:{1:88,2:80,3:72,4:64,5:58}),portraitMixedWidths={1:35,2:35,3:28,4:22,5:18},slots=mixed?(portrait?(STORY_MIXED_PORTRAIT_SLOT_X[count]||STORY_SLOT_X[count]):(STORY_MIXED_SLOT_X[count]||STORY_SLOT_X[count])):portrait?STORY_PORTRAIT_SLOT_X[count]:count===1&&storyActorKey(entities[0])!=="mira"?[100-STORY_SLOT_X[1][0]]:STORY_SLOT_X[count];
    // One reference height per formation (Mira-sized art); every actor keeps the same body scale, shrunk together only when bodies cannot fit their slots.
    const vw=innerWidth,vh=innerHeight,spacing=count>1?(slots[1]-slots[0])*vw/100:vw,fitWidth=count===1?vw*(portrait?.92:.42):spacing*(portrait?(mixed?1.5:1.9):.96),bodyScaleOf=node=>{const body=STORY_ACTOR_BODY[storyActorKey(node)];return body.h*(STORY_ACTOR_BODY.mira.b-STORY_ACTOR_BODY.mira.t)/(body.b-body.t);};
    let boxHeight=actorHeights[count]*vh/100;
    actors.slice(0,count).forEach(node=>{if(!node.naturalHeight)node.addEventListener("load",queueStoryActorLayout,{once:true});const body=STORY_ACTOR_BODY[storyActorKey(node)],aspect=node.naturalHeight?node.naturalWidth/node.naturalHeight:.667,bodyWidth=boxHeight*bodyScaleOf(node)*aspect*body.wf;if(bodyWidth>fitWidth)boxHeight*=fitWidth/bodyWidth;});
    // Portrait: a centred speaker must not run under the page title (P-00 centres its chapter title).
    const titleBottom=portrait?[...document.querySelectorAll(".chapter,.chapter-id")].map(node=>node.getBoundingClientRect()).filter(rect=>rect.height>0&&rect.bottom<vh*.3).reduce((bottom,rect)=>Math.max(bottom,rect.bottom),0):0;
    if(titleBottom){const room=vh-(mixed?Math.max(18,30-count*3)*vh/100:0)-titleBottom-12;actors.slice(0,count).forEach(node=>{const body=STORY_ACTOR_BODY[storyActorKey(node)],bodyHeight=boxHeight*bodyScaleOf(node)*(body.b-body.t);if(bodyHeight>room)boxHeight*=room/bodyHeight;});}
    const speakerName=String(document.querySelector("#speaker,.dialogue .speaker strong")?.textContent||"").trim(),speakerKey=(STORY_SPEAKER_ACTOR.find(([name])=>speakerName.startsWith(name))||[])[1]||"",dialogueBox=document.querySelector("#textbox")||document.querySelector(".dialogue"),dialogueZ=parseInt(dialogueBox?getComputedStyle(dialogueBox).zIndex:"",10),zTop=Number.isFinite(dialogueZ)&&dialogueZ>4?dialogueZ-1:15;
    entities.forEach((entity,index)=>{const threat=threats.includes(entity),bossThreat=entity.matches(".warden,.echo"),actorKey=`${entity.id||""} ${entity.getAttribute("src")||""}`.toLowerCase(),body=STORY_ACTOR_BODY[storyActorKey(entity)],bodyScale=threat?1:bodyScaleOf(entity),artCap=entity.naturalHeight?STORY_MAX_ART_UPSCALE*entity.naturalHeight/boxHeight:Infinity,actorScale=threat?1:actorKey.includes("haneul")?Math.min(bodyScale,artCap):bodyScale,listener=legacyListener.includes(entity)||entity.classList.contains("dim"),speaker=!threat&&!listener&&speakerKey!==""&&storyActorKey(entity)===speakerKey;entity.dataset.afStorySlot=String(index+1);entity.dataset.afStoryEntityCount=String(count);entity.dataset.afStoryEntityRole=threat?"threat":"actor";entity.dataset.afStoryFocus=threat?"threat":speaker?"speaker":listener?"listener":"present";entity.dataset.afStoryOpticalScale=String(Math.round(actorScale*1000)/1000);entity.style.setProperty("left",`${slots[index]}%`,"important");entity.style.setProperty("right","auto","important");entity.style.setProperty("width","auto","important");entity.style.setProperty("transition","opacity .28s, filter .28s","important");entity.style.setProperty("z-index",String(threat?zTop-2:speaker?zTop:listener?zTop-3:zTop-1),"important");if(threat){entity.style.setProperty("transform",`translateX(-50%) scale(${actorScale})`,"important");entity.style.setProperty("transform-origin","50% 100%","important");entity.style.setProperty("top",bossThreat?(portrait?"18%":"13%"):"auto","important");entity.style.setProperty("bottom",bossThreat?"auto":portrait?"34%":"28%","important");entity.style.setProperty("height",bossThreat?(portrait?`${Math.max(29,46-count*3)}svh`:`${Math.max(34,58-count*3)}vh`):(portrait?`${Math.max(17,26-count*2)}svh`:`${Math.max(20,34-count*3)}vh`),"important");entity.style.setProperty("max-width",portrait?`${portraitMixedWidths[count]}vw`:bossThreat?"28vw":"22vw","important");}else{const cx=Math.round(body.cx*1000)/10,drop=Math.round((1-body.b)*actorScale*1000)/10;entity.style.setProperty("transform",`translateX(-${cx}%) translateY(${drop}%) scale(${actorScale})`,"important");entity.style.setProperty("transform-origin",`${cx}% 100%`,"important");entity.style.setProperty("top","auto","important");entity.style.setProperty("bottom",mixed?(portrait?`${Math.max(18,30-count*3)}svh`:"28vh"):"0","important");entity.style.setProperty("height",`${Math.round(boxHeight)}px`,"important");entity.style.setProperty("max-height","none","important");entity.style.setProperty("max-width","none","important");if(entity.matches("img.operator")){if(legacyListener.includes(entity))entity.style.setProperty("filter","brightness(.64) saturate(.5) drop-shadow(0 18px 32px rgba(0,0,0,.72))","important");else entity.style.removeProperty("filter");}}});
    document.body.dataset.afStoryActorCount=String(actors.length);document.body.dataset.afStoryThreatCount=String(threats.length);document.body.dataset.afStoryEntityCount=String(count);document.body.dataset.afStoryFormation=mixed?"responsive-mixed-entity":"responsive-actor-only";
  };
  const queueStoryActorLayout=()=>{if(actorLayoutQueued)return;actorLayoutQueued=true;requestAnimationFrame(layoutStoryActors);};
  const setupStoryActorLayout=()=>{queueStoryActorLayout();new MutationObserver(queueStoryActorLayout).observe(document.body,{subtree:true,attributes:true,attributeFilter:["class","data-speaker","data-mode","data-encounter"]});addEventListener("resize",queueStoryActorLayout);addEventListener("orientationchange",queueStoryActorLayout);};
  const directScreen=()=>decodeURIComponent(location.pathname.split("/").pop()||"").replace(/\.html$/i,"");
  const guardCanonicalDirectNavigation=event=>{
    const screen=directScreen(),route=routeForScreen(screen),target=nextScreen(screen);if(!route||!target)return;
    const card=document.querySelector("#chapterCard.show"),copy=card?.textContent||"",canonicalFinal=screen==="p07intro"?copy.includes("MIDBOSS"):copy.includes("NEXT //");if(!canonicalFinal)return;
    if(event.type==="keydown"&&!(["Space","Enter"].includes(event.code)))return;
    if(event.type==="pointerup"&&event.target.closest?.("button,#history"))return;
    event.preventDefault();event.stopImmediatePropagation();dispatchNavigation(target);
  };
  if(typeof document!=="undefined"){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",setupStoryActorLayout,{once:true});else setupStoryActorLayout();addEventListener("pointerup",guardCanonicalDirectNavigation,{capture:true});addEventListener("keydown",guardCanonicalDirectNavigation,{capture:true});}
  window.AfterSignalStageFlow=freeze({version:"1.1.0",PENDING_KEY,routes:freeze(rows),normalizeStage,routeForStage,routeForScreen,nextScreen,queueBattleCompletion,dispatchNavigation,completeBattle,continueFrom,layoutStoryActors});
})();
