/* Windows/browser support tooling that exercises the same production runtime contracts. */
(() => { "use strict";
  const events=[],PROFILE_KEY="aftersignal:profile:v3";
  const push=(type,data={})=>{const event={at:Date.now(),type,data};events.push(event);return event};
  const runner=()=>window.__AF_COMMON_COMBAT_RUNNER__||window.__AF_ACTIVE_RUNNER__||window.AfterSignalCommonCombatRuntime?.active?.()||null;
  const currentStage=()=>document.body?.dataset?.stageId||window.AfterSignalFoundation?.STAGE_REGISTRY?.keys?.().next?.().value||null;
  const stageJump=stageId=>{const flow=window.AfterSignalStageFlow,route=flow?.routeForStage?.(stageId);if(!route)throw new Error(`Unknown stage ${stageId}`);push("stageJump",{stageId:route.stageId,screen:route.entry});return flow.dispatchNavigation(route.entry)};
  const unlock=characterId=>{
    const registry=window.AfterSignalFoundation?.CHARACTER_REGISTRY;if(registry&&!registry.has(characterId))throw new Error(`Unknown character ${characterId}`);
    let profile={version:"3.0",unlockedCharacterIds:[],characters:{}};try{profile={...profile,...JSON.parse(localStorage.getItem(PROFILE_KEY)||"null")}}catch{}
    profile.unlockedCharacterIds=[...new Set([...(profile.unlockedCharacterIds||[]),characterId])];profile.characters={...(profile.characters||{}),[characterId]:{...(profile.characters?.[characterId]||{}),unlocked:true}};
    localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));window.dispatchEvent(new CustomEvent("aftersignal:profile",{detail:profile}));push("unlock",{characterId});return profile;
  };
  const setParty=(stageIdOrIds,maybeIds)=>{const stageId=Array.isArray(stageIdOrIds)?currentStage():stageIdOrIds,ids=Array.isArray(stageIdOrIds)?stageIdOrIds:maybeIds;if(!stageId||!Array.isArray(ids))throw new Error("setParty requires a stage and character array");const result=window.AfterSignalCommonCombatRuntime?.configureParty?.(stageId,ids);if(!result)throw new Error("Common combat party runtime is unavailable");push("party",{stageId,ids:[...ids]});return result};
  const spawnEnemy=enemyId=>{const active=runner();if(!active?.spawnEnemy)throw new Error("Active common combat runner is unavailable");const enemy=active.spawnEnemy({enemyId,id:`qa-${Date.now().toString(36)}`,x:active.width*.5,y:active.height*.35,runtime:{runtimeMaxHp:100}});push("spawnEnemy",{enemyId,id:enemy.id});return enemy};
  const forceUltimate=characterId=>{const active=runner();if(!active?.castUltimate)throw new Error("Active common combat runner is unavailable");const index=active.players?.findIndex?.(player=>player.spec?.id===characterId)??-1;if(index<0)throw new Error(`Character ${characterId} is not in the active party`);active.session?.select?.(index);const player=active.players[index];player.member.ultimateGauge=100;active.running=true;const used=active.castUltimate();push("forceUltimate",{characterId,used});return used};
  const forceTerminalClear=()=>{const active=runner();if(!active?.update)throw new Error("Active common combat runner is unavailable");active.wave=Math.max(0,(active.session?.battleSpec?.waves?.length||1)-1);const required=Math.max(1,Number(active.session?.battleSpec?.objective?.minDistinctContributors)||1),contributors=active.players.filter(Boolean).slice(0,required).map(player=>player.spec.id);active.waveContributors=new Set(contributors);active.enemies.length=0;active.projectiles.length=0;active.enemyProjectiles.length=0;active.running=true;active.update(.016);active.publishRuntimeQa?.(0);push("forceTerminalClear",{stageId:active.stageId,contributors,completed:Boolean(active.completed)});return Boolean(active.completed)};
  const releaseCombat=()=>{const active=runner();if(!active?.dispose)throw new Error("Active common combat runner is unavailable");const released=active.dispose("qa-release");push("releaseCombat",{stageId:active.stageId,released,audit:active.lastDisposeAudit||null});return{released,audit:active.lastDisposeAudit||null}};
  const inspect=kind=>{const active=runner(),value=kind==="party"?active?.players?.map(player=>({id:player.spec?.id,x:player.x,y:player.y,state:player.controller?.state,hp:player.member?.hp})):kind==="enemies"?active?.enemies?.map(enemy=>({id:enemy.spec?.id,x:enemy.x,y:enemy.y,hp:enemy.hp,layer:enemy.renderLayer})):kind==="layers"?window.AfterSignalFinalLayerRegistry||null:kind==="save"?JSON.parse(localStorage.getItem(PROFILE_KEY)||"null"):{stageId:active?.stageId||currentStage(),running:Boolean(active?.running),partySize:active?.players?.length||0,enemyCount:active?.enemies?.length||0,failedSources:active?.failedSources?.size||0};push("inspect",{kind});return value};
  window.AfterSignalDebug=Object.freeze({events,stageJump,unlock,setParty,spawnEnemy,forceUltimate,forceTerminalClear,releaseCombat,inspect,exportLog:()=>JSON.stringify(events)});
  // Browser-visible QA controls exercise the same public debug contract. They
  // exist only for an explicit ?qa=1 launch and never alter the player build.
  const mountBrowserQaControls=()=>{
    if(!/(?:^|[?&])qa(?:=1)?(?:&|$)/.test(window.location?.search||"")||document.querySelector("#af-browser-qa-controls"))return;
    const panel=document.createElement("aside");panel.id="af-browser-qa-controls";panel.setAttribute("aria-label","AFTER SIGNAL browser QA controls");panel.style.cssText="position:fixed;left:max(6px,env(safe-area-inset-left));bottom:96px;z-index:140;display:flex;gap:4px;padding:5px;background:#020a12dd;border:1px solid #65eaff;font:700 9px ui-monospace;color:#dffaff";
    for(const id of ["mira","haneul","sera"]){const button=document.createElement("button");button.type="button";button.dataset.afForceUltimate=id;button.textContent=`QA ULT ${id.toUpperCase()}`;button.style.cssText="padding:5px 7px;border:1px solid #65eaff;background:#061824;color:#eaffff;font:inherit;cursor:pointer";button.onclick=()=>{try{const used=forceUltimate(id);panel.dataset.lastResult=`${id}:${used?"used":"rejected"}`;}catch(error){panel.dataset.lastResult=`${id}:error`;panel.title=String(error);}};panel.append(button);}
    const clear=document.createElement("button");clear.type="button";clear.dataset.afForceTerminalClear="";clear.textContent="QA CLEAR";clear.style.cssText="padding:5px 7px;border:1px solid #ffbd60;background:#261500;color:#fff2d1;font:inherit;cursor:pointer";clear.onclick=()=>{try{const completed=forceTerminalClear();panel.dataset.lastResult=`clear:${completed?"completed":"rejected"}`;}catch(error){panel.dataset.lastResult="clear:error";panel.title=String(error);}};panel.append(clear);
    const release=document.createElement("button");release.type="button";release.dataset.afReleaseCombat="";release.textContent="QA RELEASE";release.style.cssText="padding:5px 7px;border:1px solid #ff7ea8;background:#2b0715;color:#ffe6ef;font:inherit;cursor:pointer";release.onclick=()=>{try{const result=releaseCombat();panel.dataset.lastResult=`release:${result.released?"released":"rejected"}`;}catch(error){panel.dataset.lastResult="release:error";panel.title=String(error);}};panel.append(release);
    document.body.append(panel);
  };
  if(document.readyState==="loading")addEventListener("DOMContentLoaded",mountBrowserQaControls,{once:true});else mountBrowserQaControls();
})();
